                    <h5 class="widget-name"><i class="icon-external-link"></i>View Grade</h5>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="widget">
                                <div class="navbar">
                                    <div class="navbar-inner">
                                        <h6><i class="icon-th-large"></i>Grade Details</h6>
                                        <a class="btn btn-info pull-right" href="/admin/education/grades/edit/<?php echo $this->recordId; ?>"><b class="icon-pencil"></b>Edit Grade</a>
                                        <a class="btn btn-inverse pull-right" href="/admin/education/grades"><b class="icon-table"></b>Return to List</a>
                                    </div>
                                </div>
                                <div class="well">
<?php
echo $this->partial('admin/form-readonly-partial', array(
    'form'     => $this->form,
    'fieldset' => 'gradefieldset',
));
?>
                                </div>
                            </div>
                        </div>
                    </div>
