<div class="login">
	<div class="navbar">
		<div class="navbar-inner">
			<h6><i class="icon-th"></i>Learning App Lock Platform</h6>
		</div>
	</div>
	<div class="well">
		<form method="POST" name="login-form" action="/login" class="row-fluid" id="login-form">
			<div class="control-group">
				<label class="control-label">Username</label>
				<div class="controls">
					<input type="text" name="login-fieldset&#x5B;username&#x5D;" required="required" class="validate&#x5B;required&#x5D;&#x20;span12" placeholder="Enter&#x20;your&#x20;username" value="">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">Password</label>
				<div class="controls">
 					<input type="password" name="login-fieldset&#x5B;password&#x5D;" required="required" class="validate&#x5B;required&#x5D;&#x20;span12" placeholder="Hidden&#x20;for&#x20;security" value="">
				</div>
			</div>
			<div class="control-group">
				<div class="controls">
					<input type="hidden" name="login-fieldset&#x5B;rememberme&#x5D;" value="0"><input type="checkbox" name="login-fieldset&#x5B;rememberme&#x5D;" class="styled" value="1"> Remember me
				</div>
			</div>
			<div class="login-btn">
				<input type="submit" value="Login" class="btn btn-danger btn-block" />
			</div>
		</form>
	</div>
</div>