<?php

namespace DoctrineORMModule\Proxy\__CG__\LundSite\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProductRegistration extends \LundSite\Entity\ProductRegistration implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'createdAt', 'createdBy', 'modifiedAt', 'modifiedBy', 'deleted', 'disabled', 'title', 'firstName', 'middleInitial', 'lastName', 'emailAddress', 'streetAddress', 'extStreetAddress', 'locality', 'postCode', 'phoneNumber', 'birthDate', 'maritalStatus', 'upcCode', 'ownedLength', 'pricePaid', 'wherePurchased', 'installer', 'shopStore', 'shopOnline', 'shopCatalog', 'brandInMind', 'brandPurchased', 'easeOfInstallation', 'quality', 'valueOfMoney', 'overall', 'infReputation', 'infEase', 'infDealer', 'infRecommendation', 'infFunctionality', 'infAvailability', 'infPrice', 'infStyle', 'infQuality', 'infWarranty', 'infOther', 'personOneGender', 'personOneAge', 'personTwoGender', 'personTwoAge', 'personThreeGender', 'personThreeAge', 'personFourGender', 'personFourAge', 'noneHousehold', 'childUnderOne', 'youOccupation', 'spouseOccupation', 'youHomemaker', 'spouseHomemaker', 'youRetired', 'spouseRetired', 'youStudent', 'spouseStudent', 'youOwner', 'spouseOwner', 'youHome', 'spouseHome', 'youMilitary', 'spouseMilitary', 'youVeteran', 'spouseVeteran', 'income', 'education', 'creditCards', 'residence', 'magazineSubscribed', 'magazinePurchased', 'newWithin', 'usedWithin', 'purchaseType', 'optout', 'productRegistrationId', 'site', 'region', 'country', 'productCategory', 'vehYear', 'vehMake', 'vehModel', 'vehSubmodel', 'recVehYear', 'recVehMake', 'recVehModel', 'recVehSubmodel', 'aboutHousehold', 'lifestyleHousehold');
        }

        return array('__isInitialized__', 'createdAt', 'createdBy', 'modifiedAt', 'modifiedBy', 'deleted', 'disabled', 'title', 'firstName', 'middleInitial', 'lastName', 'emailAddress', 'streetAddress', 'extStreetAddress', 'locality', 'postCode', 'phoneNumber', 'birthDate', 'maritalStatus', 'upcCode', 'ownedLength', 'pricePaid', 'wherePurchased', 'installer', 'shopStore', 'shopOnline', 'shopCatalog', 'brandInMind', 'brandPurchased', 'easeOfInstallation', 'quality', 'valueOfMoney', 'overall', 'infReputation', 'infEase', 'infDealer', 'infRecommendation', 'infFunctionality', 'infAvailability', 'infPrice', 'infStyle', 'infQuality', 'infWarranty', 'infOther', 'personOneGender', 'personOneAge', 'personTwoGender', 'personTwoAge', 'personThreeGender', 'personThreeAge', 'personFourGender', 'personFourAge', 'noneHousehold', 'childUnderOne', 'youOccupation', 'spouseOccupation', 'youHomemaker', 'spouseHomemaker', 'youRetired', 'spouseRetired', 'youStudent', 'spouseStudent', 'youOwner', 'spouseOwner', 'youHome', 'spouseHome', 'youMilitary', 'spouseMilitary', 'youVeteran', 'spouseVeteran', 'income', 'education', 'creditCards', 'residence', 'magazineSubscribed', 'magazinePurchased', 'newWithin', 'usedWithin', 'purchaseType', 'optout', 'productRegistrationId', 'site', 'region', 'country', 'productCategory', 'vehYear', 'vehMake', 'vehModel', 'vehSubmodel', 'recVehYear', 'recVehMake', 'recVehModel', 'recVehSubmodel', 'aboutHousehold', 'lifestyleHousehold');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProductRegistration $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedAt($modifiedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedAt', array($modifiedAt));

        return parent::setModifiedAt($modifiedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedAt', array());

        return parent::getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedBy($modifiedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedBy', array($modifiedBy));

        return parent::setModifiedBy($modifiedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedBy', array());

        return parent::getModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', array($deleted));

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', array());

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisabled($disabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisabled', array($disabled));

        return parent::setDisabled($disabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisabled', array());

        return parent::getDisabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', array($firstName));

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', array());

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setMiddleInitial($middleInitial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMiddleInitial', array($middleInitial));

        return parent::setMiddleInitial($middleInitial);
    }

    /**
     * {@inheritDoc}
     */
    public function getMiddleInitial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMiddleInitial', array());

        return parent::getMiddleInitial();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', array($lastName));

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', array());

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailAddress($emailAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailAddress', array($emailAddress));

        return parent::setEmailAddress($emailAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailAddress', array());

        return parent::getEmailAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreetAddress($streetAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreetAddress', array($streetAddress));

        return parent::setStreetAddress($streetAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreetAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreetAddress', array());

        return parent::getStreetAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtStreetAddress($extStreetAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtStreetAddress', array($extStreetAddress));

        return parent::setExtStreetAddress($extStreetAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtStreetAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtStreetAddress', array());

        return parent::getExtStreetAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocality($locality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocality', array($locality));

        return parent::setLocality($locality);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocality', array());

        return parent::getLocality();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostCode($postCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostCode', array($postCode));

        return parent::setPostCode($postCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostCode', array());

        return parent::getPostCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber($phoneNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', array($phoneNumber));

        return parent::setPhoneNumber($phoneNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', array());

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthDate($birthDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthDate', array($birthDate));

        return parent::setBirthDate($birthDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthDate', array());

        return parent::getBirthDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaritalStatus($maritalStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaritalStatus', array($maritalStatus));

        return parent::setMaritalStatus($maritalStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaritalStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaritalStatus', array());

        return parent::getMaritalStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpcCode($upcCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpcCode', array($upcCode));

        return parent::setUpcCode($upcCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpcCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpcCode', array());

        return parent::getUpcCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwnedLength($ownedLength)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwnedLength', array($ownedLength));

        return parent::setOwnedLength($ownedLength);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwnedLength()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwnedLength', array());

        return parent::getOwnedLength();
    }

    /**
     * {@inheritDoc}
     */
    public function setPricePaid($pricePaid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPricePaid', array($pricePaid));

        return parent::setPricePaid($pricePaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPricePaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPricePaid', array());

        return parent::getPricePaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setWherePurchased($wherePurchased)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWherePurchased', array($wherePurchased));

        return parent::setWherePurchased($wherePurchased);
    }

    /**
     * {@inheritDoc}
     */
    public function getWherePurchased()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWherePurchased', array());

        return parent::getWherePurchased();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstaller($installer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstaller', array($installer));

        return parent::setInstaller($installer);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstaller()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstaller', array());

        return parent::getInstaller();
    }

    /**
     * {@inheritDoc}
     */
    public function setShopStore($shopStore)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShopStore', array($shopStore));

        return parent::setShopStore($shopStore);
    }

    /**
     * {@inheritDoc}
     */
    public function getShopStore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShopStore', array());

        return parent::getShopStore();
    }

    /**
     * {@inheritDoc}
     */
    public function setShopOnline($shopOnline)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShopOnline', array($shopOnline));

        return parent::setShopOnline($shopOnline);
    }

    /**
     * {@inheritDoc}
     */
    public function getShopOnline()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShopOnline', array());

        return parent::getShopOnline();
    }

    /**
     * {@inheritDoc}
     */
    public function setShopCatalog($shopCatalog)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShopCatalog', array($shopCatalog));

        return parent::setShopCatalog($shopCatalog);
    }

    /**
     * {@inheritDoc}
     */
    public function getShopCatalog()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShopCatalog', array());

        return parent::getShopCatalog();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrandInMind($brandInMind)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrandInMind', array($brandInMind));

        return parent::setBrandInMind($brandInMind);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrandInMind()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrandInMind', array());

        return parent::getBrandInMind();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrandPurchased($brandPurchased)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrandPurchased', array($brandPurchased));

        return parent::setBrandPurchased($brandPurchased);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrandPurchased()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrandPurchased', array());

        return parent::getBrandPurchased();
    }

    /**
     * {@inheritDoc}
     */
    public function setEaseOfInstallation($easeOfInstallation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEaseOfInstallation', array($easeOfInstallation));

        return parent::setEaseOfInstallation($easeOfInstallation);
    }

    /**
     * {@inheritDoc}
     */
    public function getEaseOfInstallation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEaseOfInstallation', array());

        return parent::getEaseOfInstallation();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuality($quality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuality', array($quality));

        return parent::setQuality($quality);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuality', array());

        return parent::getQuality();
    }

    /**
     * {@inheritDoc}
     */
    public function setValueOfMoney($valueOfMoney)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValueOfMoney', array($valueOfMoney));

        return parent::setValueOfMoney($valueOfMoney);
    }

    /**
     * {@inheritDoc}
     */
    public function getValueOfMoney()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValueOfMoney', array());

        return parent::getValueOfMoney();
    }

    /**
     * {@inheritDoc}
     */
    public function setOverall($overall)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOverall', array($overall));

        return parent::setOverall($overall);
    }

    /**
     * {@inheritDoc}
     */
    public function getOverall()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOverall', array());

        return parent::getOverall();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfReputation($infReputation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfReputation', array($infReputation));

        return parent::setInfReputation($infReputation);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfReputation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfReputation', array());

        return parent::getInfReputation();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfEase($infEase)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfEase', array($infEase));

        return parent::setInfEase($infEase);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfEase()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfEase', array());

        return parent::getInfEase();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfDealer($infDealer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfDealer', array($infDealer));

        return parent::setInfDealer($infDealer);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfDealer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfDealer', array());

        return parent::getInfDealer();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfRecommendation($infRecommendation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfRecommendation', array($infRecommendation));

        return parent::setInfRecommendation($infRecommendation);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfRecommendation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfRecommendation', array());

        return parent::getInfRecommendation();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfFunctionality($infFunctionality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfFunctionality', array($infFunctionality));

        return parent::setInfFunctionality($infFunctionality);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfFunctionality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfFunctionality', array());

        return parent::getInfFunctionality();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfAvailability($infAvailability)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfAvailability', array($infAvailability));

        return parent::setInfAvailability($infAvailability);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfAvailability()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfAvailability', array());

        return parent::getInfAvailability();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfPrice($infPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfPrice', array($infPrice));

        return parent::setInfPrice($infPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfPrice', array());

        return parent::getInfPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfStyle($infStyle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfStyle', array($infStyle));

        return parent::setInfStyle($infStyle);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfStyle', array());

        return parent::getInfStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfQuality($infQuality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfQuality', array($infQuality));

        return parent::setInfQuality($infQuality);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfQuality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfQuality', array());

        return parent::getInfQuality();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfWarranty($infWarranty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfWarranty', array($infWarranty));

        return parent::setInfWarranty($infWarranty);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfWarranty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfWarranty', array());

        return parent::getInfWarranty();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfOther($infOther)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfOther', array($infOther));

        return parent::setInfOther($infOther);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfOther()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfOther', array());

        return parent::getInfOther();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonOneGender($personOneGender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonOneGender', array($personOneGender));

        return parent::setPersonOneGender($personOneGender);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonOneGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonOneGender', array());

        return parent::getPersonOneGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonOneAge($personOneAge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonOneAge', array($personOneAge));

        return parent::setPersonOneAge($personOneAge);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonOneAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonOneAge', array());

        return parent::getPersonOneAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonTwoGender($personTwoGender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonTwoGender', array($personTwoGender));

        return parent::setPersonTwoGender($personTwoGender);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonTwoGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonTwoGender', array());

        return parent::getPersonTwoGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonTwoAge($personTwoAge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonTwoAge', array($personTwoAge));

        return parent::setPersonTwoAge($personTwoAge);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonTwoAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonTwoAge', array());

        return parent::getPersonTwoAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonThreeGender($personThreeGender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonThreeGender', array($personThreeGender));

        return parent::setPersonThreeGender($personThreeGender);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonThreeGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonThreeGender', array());

        return parent::getPersonThreeGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonThreeAge($personThreeAge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonThreeAge', array($personThreeAge));

        return parent::setPersonThreeAge($personThreeAge);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonThreeAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonThreeAge', array());

        return parent::getPersonThreeAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonFourGender($personFourGender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonFourGender', array($personFourGender));

        return parent::setPersonFourGender($personFourGender);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonFourGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonFourGender', array());

        return parent::getPersonFourGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonFourAge($personFourAge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonFourAge', array($personFourAge));

        return parent::setPersonFourAge($personFourAge);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonFourAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonFourAge', array());

        return parent::getPersonFourAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoneHousehold($noneHousehold)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoneHousehold', array($noneHousehold));

        return parent::setNoneHousehold($noneHousehold);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoneHousehold()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoneHousehold', array());

        return parent::getNoneHousehold();
    }

    /**
     * {@inheritDoc}
     */
    public function setChildUnderOne($childUnderOne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChildUnderOne', array($childUnderOne));

        return parent::setChildUnderOne($childUnderOne);
    }

    /**
     * {@inheritDoc}
     */
    public function getChildUnderOne()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildUnderOne', array());

        return parent::getChildUnderOne();
    }

    /**
     * {@inheritDoc}
     */
    public function setYouOccupation($youOccupation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYouOccupation', array($youOccupation));

        return parent::setYouOccupation($youOccupation);
    }

    /**
     * {@inheritDoc}
     */
    public function getYouOccupation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYouOccupation', array());

        return parent::getYouOccupation();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpouseOccupation($spouseOccupation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpouseOccupation', array($spouseOccupation));

        return parent::setSpouseOccupation($spouseOccupation);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpouseOccupation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpouseOccupation', array());

        return parent::getSpouseOccupation();
    }

    /**
     * {@inheritDoc}
     */
    public function setYouHomemaker($youHomemaker)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYouHomemaker', array($youHomemaker));

        return parent::setYouHomemaker($youHomemaker);
    }

    /**
     * {@inheritDoc}
     */
    public function getYouHomemaker()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYouHomemaker', array());

        return parent::getYouHomemaker();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpouseHomemaker($spouseHomemaker)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpouseHomemaker', array($spouseHomemaker));

        return parent::setSpouseHomemaker($spouseHomemaker);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpouseHomemaker()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpouseHomemaker', array());

        return parent::getSpouseHomemaker();
    }

    /**
     * {@inheritDoc}
     */
    public function setYouRetired($youRetired)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYouRetired', array($youRetired));

        return parent::setYouRetired($youRetired);
    }

    /**
     * {@inheritDoc}
     */
    public function getYouRetired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYouRetired', array());

        return parent::getYouRetired();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpouseRetired($spouseRetired)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpouseRetired', array($spouseRetired));

        return parent::setSpouseRetired($spouseRetired);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpouseRetired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpouseRetired', array());

        return parent::getSpouseRetired();
    }

    /**
     * {@inheritDoc}
     */
    public function setYouStudent($youStudent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYouStudent', array($youStudent));

        return parent::setYouStudent($youStudent);
    }

    /**
     * {@inheritDoc}
     */
    public function getYouStudent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYouStudent', array());

        return parent::getYouStudent();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpouseStudent($spouseStudent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpouseStudent', array($spouseStudent));

        return parent::setSpouseStudent($spouseStudent);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpouseStudent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpouseStudent', array());

        return parent::getSpouseStudent();
    }

    /**
     * {@inheritDoc}
     */
    public function setYouOwner($youOwner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYouOwner', array($youOwner));

        return parent::setYouOwner($youOwner);
    }

    /**
     * {@inheritDoc}
     */
    public function getYouOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYouOwner', array());

        return parent::getYouOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpouseOwner($spouseOwner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpouseOwner', array($spouseOwner));

        return parent::setSpouseOwner($spouseOwner);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpouseOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpouseOwner', array());

        return parent::getSpouseOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setYouHome($youHome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYouHome', array($youHome));

        return parent::setYouHome($youHome);
    }

    /**
     * {@inheritDoc}
     */
    public function getYouHome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYouHome', array());

        return parent::getYouHome();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpouseHome($spouseHome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpouseHome', array($spouseHome));

        return parent::setSpouseHome($spouseHome);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpouseHome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpouseHome', array());

        return parent::getSpouseHome();
    }

    /**
     * {@inheritDoc}
     */
    public function setYouMilitary($youMilitary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYouMilitary', array($youMilitary));

        return parent::setYouMilitary($youMilitary);
    }

    /**
     * {@inheritDoc}
     */
    public function getYouMilitary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYouMilitary', array());

        return parent::getYouMilitary();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpouseMilitary($spouseMilitary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpouseMilitary', array($spouseMilitary));

        return parent::setSpouseMilitary($spouseMilitary);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpouseMilitary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpouseMilitary', array());

        return parent::getSpouseMilitary();
    }

    /**
     * {@inheritDoc}
     */
    public function setYouVeteran($youVeteran)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYouVeteran', array($youVeteran));

        return parent::setYouVeteran($youVeteran);
    }

    /**
     * {@inheritDoc}
     */
    public function getYouVeteran()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYouVeteran', array());

        return parent::getYouVeteran();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpouseVeteran($spouseVeteran)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpouseVeteran', array($spouseVeteran));

        return parent::setSpouseVeteran($spouseVeteran);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpouseVeteran()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpouseVeteran', array());

        return parent::getSpouseVeteran();
    }

    /**
     * {@inheritDoc}
     */
    public function setIncome($income)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncome', array($income));

        return parent::setIncome($income);
    }

    /**
     * {@inheritDoc}
     */
    public function getIncome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncome', array());

        return parent::getIncome();
    }

    /**
     * {@inheritDoc}
     */
    public function setEducation($education)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEducation', array($education));

        return parent::setEducation($education);
    }

    /**
     * {@inheritDoc}
     */
    public function getEducation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEducation', array());

        return parent::getEducation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreditCards($creditCards)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreditCards', array($creditCards));

        return parent::setCreditCards($creditCards);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditCards()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditCards', array());

        return parent::getCreditCards();
    }

    /**
     * {@inheritDoc}
     */
    public function setResidence($residence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResidence', array($residence));

        return parent::setResidence($residence);
    }

    /**
     * {@inheritDoc}
     */
    public function getResidence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResidence', array());

        return parent::getResidence();
    }

    /**
     * {@inheritDoc}
     */
    public function setMagazineSubscribed($magazineSubscribed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMagazineSubscribed', array($magazineSubscribed));

        return parent::setMagazineSubscribed($magazineSubscribed);
    }

    /**
     * {@inheritDoc}
     */
    public function getMagazineSubscribed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMagazineSubscribed', array());

        return parent::getMagazineSubscribed();
    }

    /**
     * {@inheritDoc}
     */
    public function setMagazinePurchased($magazinePurchased)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMagazinePurchased', array($magazinePurchased));

        return parent::setMagazinePurchased($magazinePurchased);
    }

    /**
     * {@inheritDoc}
     */
    public function getMagazinePurchased()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMagazinePurchased', array());

        return parent::getMagazinePurchased();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewWithin($newWithin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewWithin', array($newWithin));

        return parent::setNewWithin($newWithin);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewWithin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewWithin', array());

        return parent::getNewWithin();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsedWithin($usedWithin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsedWithin', array($usedWithin));

        return parent::setUsedWithin($usedWithin);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsedWithin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsedWithin', array());

        return parent::getUsedWithin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPurchaseType($purchaseType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPurchaseType', array($purchaseType));

        return parent::setPurchaseType($purchaseType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPurchaseType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPurchaseType', array());

        return parent::getPurchaseType();
    }

    /**
     * {@inheritDoc}
     */
    public function setOptout($optout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptout', array($optout));

        return parent::setOptout($optout);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptout', array());

        return parent::getOptout();
    }

    /**
     * {@inheritDoc}
     */
    public function getProductRegistrationId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getProductRegistrationId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductRegistrationId', array());

        return parent::getProductRegistrationId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSite(\RocketCms\Entity\Site $site = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSite', array($site));

        return parent::setSite($site);
    }

    /**
     * {@inheritDoc}
     */
    public function getSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSite', array());

        return parent::getSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegion(\RocketBase\Entity\State $region = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegion', array($region));

        return parent::setRegion($region);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegion', array());

        return parent::getRegion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry(\RocketBase\Entity\Country $country = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductCategory(\LundProducts\Entity\ProductCategories $productCategory = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductCategory', array($productCategory));

        return parent::setProductCategory($productCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductCategory', array());

        return parent::getProductCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehYear(\LundProducts\Entity\VehYear $vehYear = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehYear', array($vehYear));

        return parent::setVehYear($vehYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehYear', array());

        return parent::getVehYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehMake(\LundProducts\Entity\VehMake $vehMake = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehMake', array($vehMake));

        return parent::setVehMake($vehMake);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehMake()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehMake', array());

        return parent::getVehMake();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehModel(\LundProducts\Entity\VehModel $vehModel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehModel', array($vehModel));

        return parent::setVehModel($vehModel);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehModel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehModel', array());

        return parent::getVehModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehSubmodel(\LundProducts\Entity\VehSubmodel $vehSubmodel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehSubmodel', array($vehSubmodel));

        return parent::setVehSubmodel($vehSubmodel);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehSubmodel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehSubmodel', array());

        return parent::getVehSubmodel();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecVehYear(\LundProducts\Entity\VehYear $recVehYear = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecVehYear', array($recVehYear));

        return parent::setRecVehYear($recVehYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecVehYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecVehYear', array());

        return parent::getRecVehYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecVehMake(\LundProducts\Entity\VehMake $recVehMake = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecVehMake', array($recVehMake));

        return parent::setRecVehMake($recVehMake);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecVehMake()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecVehMake', array());

        return parent::getRecVehMake();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecVehModel(\LundProducts\Entity\VehModel $recVehModel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecVehModel', array($recVehModel));

        return parent::setRecVehModel($recVehModel);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecVehModel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecVehModel', array());

        return parent::getRecVehModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecVehSubmodel(\LundProducts\Entity\VehSubmodel $recVehSubmodel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecVehSubmodel', array($recVehSubmodel));

        return parent::setRecVehSubmodel($recVehSubmodel);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecVehSubmodel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecVehSubmodel', array());

        return parent::getRecVehSubmodel();
    }

    /**
     * {@inheritDoc}
     */
    public function addAboutHousehold(\Doctrine\Common\Collections\ArrayCollection $aboutHousehold)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAboutHousehold', array($aboutHousehold));

        return parent::addAboutHousehold($aboutHousehold);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAboutHousehold(\Doctrine\Common\Collections\ArrayCollection $aboutHousehold)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAboutHousehold', array($aboutHousehold));

        return parent::removeAboutHousehold($aboutHousehold);
    }

    /**
     * {@inheritDoc}
     */
    public function getAboutHousehold()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAboutHousehold', array());

        return parent::getAboutHousehold();
    }

    /**
     * {@inheritDoc}
     */
    public function addLifestyleHousehold(\Doctrine\Common\Collections\ArrayCollection $lifestyleHousehold)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLifestyleHousehold', array($lifestyleHousehold));

        return parent::addLifestyleHousehold($lifestyleHousehold);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLifestyleHousehold(\Doctrine\Common\Collections\ArrayCollection $lifestyleHousehold)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLifestyleHousehold', array($lifestyleHousehold));

        return parent::removeLifestyleHousehold($lifestyleHousehold);
    }

    /**
     * {@inheritDoc}
     */
    public function getLifestyleHousehold()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLifestyleHousehold', array());

        return parent::getLifestyleHousehold();
    }

}
