<?php

namespace DoctrineORMModule\Proxy\__CG__\RocketEcom\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Orders extends \RocketEcom\Entity\Orders implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'createdAt', 'createdBy', 'modifiedAt', 'modifiedBy', 'deleted', 'disabled', 'subtotal', 'taxCost', 'shippingCost', 'total', 'emailAddress', 'cardType', 'cardName', 'cardNumber', 'cardExpMonth', 'cardExpYear', 'cardCvv', 'transactionId', 'poNumber', 'orderId', 'user', 'billingAddress', 'shippingAddress', 'shippingMethod');
        }

        return array('__isInitialized__', 'createdAt', 'createdBy', 'modifiedAt', 'modifiedBy', 'deleted', 'disabled', 'subtotal', 'taxCost', 'shippingCost', 'total', 'emailAddress', 'cardType', 'cardName', 'cardNumber', 'cardExpMonth', 'cardExpYear', 'cardCvv', 'transactionId', 'poNumber', 'orderId', 'user', 'billingAddress', 'shippingAddress', 'shippingMethod');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Orders $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedAt($modifiedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedAt', array($modifiedAt));

        return parent::setModifiedAt($modifiedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedAt', array());

        return parent::getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedBy($modifiedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedBy', array($modifiedBy));

        return parent::setModifiedBy($modifiedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedBy', array());

        return parent::getModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', array($deleted));

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', array());

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisabled($disabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisabled', array($disabled));

        return parent::setDisabled($disabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisabled', array());

        return parent::getDisabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtotal($subtotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtotal', array($subtotal));

        return parent::setSubtotal($subtotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtotal', array());

        return parent::getSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxCost($taxCost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxCost', array($taxCost));

        return parent::setTaxCost($taxCost);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxCost', array());

        return parent::getTaxCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingCost($shippingCost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingCost', array($shippingCost));

        return parent::setShippingCost($shippingCost);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingCost', array());

        return parent::getShippingCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', array($total));

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', array());

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailAddress($emailAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailAddress', array($emailAddress));

        return parent::setEmailAddress($emailAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailAddress', array());

        return parent::getEmailAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardType($cardType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardType', array($cardType));

        return parent::setCardType($cardType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCardType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardType', array());

        return parent::getCardType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardName($cardName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardName', array($cardName));

        return parent::setCardName($cardName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCardName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardName', array());

        return parent::getCardName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardNumber($cardNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardNumber', array($cardNumber));

        return parent::setCardNumber($cardNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getCardNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardNumber', array());

        return parent::getCardNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardExpMonth($cardExpMonth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardExpMonth', array($cardExpMonth));

        return parent::setCardExpMonth($cardExpMonth);
    }

    /**
     * {@inheritDoc}
     */
    public function getCardExpMonth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardExpMonth', array());

        return parent::getCardExpMonth();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardExpYear($cardExpYear)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardExpYear', array($cardExpYear));

        return parent::setCardExpYear($cardExpYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getCardExpYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardExpYear', array());

        return parent::getCardExpYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardCvv($cardCvv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardCvv', array($cardCvv));

        return parent::setCardCvv($cardCvv);
    }

    /**
     * {@inheritDoc}
     */
    public function getCardCvv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardCvv', array());

        return parent::getCardCvv();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransactionId($transactionId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransactionId', array($transactionId));

        return parent::setTransactionId($transactionId);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransactionId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactionId', array());

        return parent::getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoNumber($poNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoNumber', array($poNumber));

        return parent::setPoNumber($poNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoNumber', array());

        return parent::getPoNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getOrderId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderId', array());

        return parent::getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\RocketUser\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddress(\RocketEcom\Entity\OrderAddress $billingAddress = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddress', array($billingAddress));

        return parent::setBillingAddress($billingAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress', array());

        return parent::getBillingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingAddress(\RocketEcom\Entity\OrderAddress $shippingAddress = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingAddress', array($shippingAddress));

        return parent::setShippingAddress($shippingAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingAddress', array());

        return parent::getShippingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingMethod(\RocketEcom\Entity\ShippingMethod $shippingMethod = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingMethod', array($shippingMethod));

        return parent::setShippingMethod($shippingMethod);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingMethod', array());

        return parent::getShippingMethod();
    }

}
