        <footer>
            <div class="footer-inner">
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
<script type="text/javascript" src="/assets/rocket-admin/js/plugins/ui/prettify.js"></script>
<script type="text/javascript" src="/assets/rocket-admin/js/plugins/forms/jquery.uniform.min.js"></script>
<script type="text/javascript" src="/assets/rocket-admin/js/files/bootstrap.min.js"></script>
<script type="text/javascript" src="/assets/rocket-admin/js/files/login.js"></script>
        </body>
</html>
