<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en-US"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en-US"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en-US"> <![endif]-->
<!--[if IE 9 ]><html class="ie ie9" lang="en-US"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--><html lang="en-US"> <!--<![endif]-->
	<head>
    	<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">    
        <title><?php echo (null !== $this->metaTitle ? $this->metaTitle : 'Learning App Lock'); ?></title>        
        <meta name="keywords" content="<?php echo (null !== $this->metaKeywords ? $this->metaKeywords : 'Learning App Lock'); ?>" />
        <meta name="description" content="<?php echo (null !== $this->metaDescription ? $this->metaDescription : 'Learning App Lock is the first learning app that intergrates education with Gaming'); ?>" />
        <link rel="canonical" href="http://www.learningapplock.com/" />   
		<link rel='shortlink' href='http://www.learningapplock.com/' />
        
        <!--[if lt IE 8]>
		    <div style=' clear: both; text-align:center; position: relative;'>
		    	<a href="http://www.microsoft.com/windows/internet-explorer/default.aspx?ocid=ie6_countdown_bannercode"><img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" alt="" /></a>
		    </div>
	  	<![endif]-->    
        <link href="/assets/application/learningapplock/css/bootstrap.min.css" rel="stylesheet">
        <link href="/assets/application/learningapplock/css/bootstrap-theme.min.css" rel="stylesheet">
        <link href="/assets/application/learningapplock/css/style.css" rel="stylesheet">
        <link href="/assets/rocket-admin/css/adm.main.css" media="screen" rel="stylesheet" type="text/css">

        <link href="/assets/rocket-admin/css/adm.ie8.css" media="screen" rel="stylesheet" type="text/css" conditional="if IE 8">

        <link href="/images/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">        

        <?php echo $this->headLink(); ?>
        <style>
        body{
        	background-image:none;
        }
        </style>
        
        
    </head>
    <body>
