<nav role="navigation" class="navbar navbar-default">
	<div id="navbarCollapse" class="collapse navbar-collapse">
    	<ul class="nav navbar-nav">
		<?php
          	$menu = $this->menuService->getMenuByShortCode($this->site, 'main-menu');
            $elements = $this->menuElementService->getParentElements($menu);
            $activeElement = $this->menuElementService->getMenuElementByUrl($menu, '/' . $this->page->getSlug());

            if (null != $activeElement) 
            {
                $parentElement = $activeElement->getParentMenuElement();
                if (null == $parentElement) { $parentElement = $activeElement; }
            }

            foreach ($elements as $element) 
            {
                $childElements = null;

                if (null == $element->getParentMenuElement()) 
                {
                    $childElements = $this->menuElementService->getChildrenElements($element);
            
                    ?>
                	<li class="dropdown" <?php if (null != $activeElement) { echo (($activeElement->getMenuElementId() == $element->getMenuElementId() || $parentElement->getMenuElementId() == $element->getMenuElementId()) ? ' class="active"' : ''); } ?> >
                    	<a href="<?php echo $element->getUrl(); ?>" title="<?php echo $element->getTitle(); ?>"  class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $element->getTitle(); ?></a>
                       	<?php if (null != $childElements) { ?>
                    		<ul role="menu" class="dropdown-menu">
                           		<?php foreach ($childElements as $childElement) { ?>
                        			<li class="dropdown-menu" <?php if (null != $activeElement) { echo ($activeElement->getMenuElementId() == $childElement->getMenuElementId() ? ' class="active"' : ''); } ?>><a href="<?php echo $childElement->getUrl(); ?>"<?php echo ($childElement->getAction() == 'external' ? ' target="_blank"' : ''); ?> title="<?php echo $childElement->getTitle(); ?>"><?php echo $childElement->getTitle(); ?></a></li>
                           		<?php } ?>
                   			</ul>
                       	<?php } ?>
                	</li>
                <?php } ?>
            <?php } ?>
      	</ul>
	</div>
	
<div id="navbarCollapse" class="collapse navbar-collapse">
	<ul class="nav navbar-nav">
		<li class="dropdown">
			<a href="about-us/about-us" title="About Us"  class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About Us</a>
			<ul role="menu" class="dropdown-menu">
				<li><a href="about-us/testimonials" title="Testimonials">Testimonials</a></li>
				<li><a href="about-us/archives" title="Archives">Archives</a></li>
				<li><a href="about-us/faqs" title="Faqs">Faqs</a></li>
 			</ul>
		</li>
		<li class="dropdown">
			<a data-toggle="dropdown" class="dropdown-toggle"  href="our-programs">Our Programs<b class="caret"></b></a>
			<ul role="menu" class="dropdown-menu">
				<li><a href="our-programs/elementary" title="Elementary">Elementary</a></li>
				<li><a href="our-programs/middle-school" title="Middle School">Middle School</a></li>
				<li><a href="our-programs/high-school" title="High School">High School</a></li>
			</ul>
		</li>
		<li>
			<a href="our-staff" title="Our Staff"  class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Our Staff</a>
		</li>
		<li>
			<a href="blog" title="Blog"  class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Blog</a>
		</li>
		<li>
			<a href="contact-us" title="Contact Us"  class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Contact Us</a>
		</li>
	</ul>
</div>	
	
	
	        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#">Profile</a></li>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">Messages <b class="caret"></b></a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="#">Inbox</a></li>
                        <li><a href="#">Drafts</a></li>
                        <li><a href="#">Sent Items</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Trash</a></li>
                    </ul>
                </li>
            </ul>
            <form role="search" class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" placeholder="Search" class="form-control">
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Login</a></li>
            </ul>
        </div>
</nav>
