                    <h5 class="widget-name"><i class="icon-pencil"></i>Edit Customer</h5>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="widget">
                                <a class="btn" href="/admin/accounts/accounts/edit/<?php echo $this->account; ?>"><b class="fam-layout"></b>Edit Plans</a>
                                <a class="btn" href="/admin/accounts/emails/home/<?php echo $this->account; ?>"><b class="fam-layout"></b>Edit Emails</a>
                                <div class="navbar">
                                    <div class="navbar-inner">
                                        <h6><i class="icon-th-large"></i>Customer Details</h6>
                                        <a class="btn btn-danger confirm pull-right" href="/admin/accounts/customer/delete/<?php echo $this->recordId; ?>"><b class="icon-trash"></b>Delete Customer</a>
                                    </div>
                                </div>
                                <div class="well">
<?php
echo $this->partial('admin/form-partial', array(
    'form'     => $this->form,
    'url'      => '/admin/accounts/customer/edit/' . $this->recordId,
    'fieldset' => 'customer-fieldset',
));
?>
                                </div>
                            </div>
                        </div>
                    </div>
