                    <h5 class="widget-name"><i class="icon-external-link"></i>View Customer</h5>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="widget">
                                <a class="btn" href="/admin/accounts/accounts/view/<?php echo $this->account; ?>"><b class="fam-layout"></b>View Plans</a>
                                <a class="btn" href="/admin/accounts/emails/view/<?php echo $this->account; ?>"><b class="fam-layout"></b>View Emails</a>
                                <div class="navbar">
                                    <div class="navbar-inner">
                                        <h6><i class="icon-th-large"></i>Customer Customer</h6>
                                        <a class="btn btn-info pull-right" href="/admin/accounts/customer/edit/<?php echo $this->recordId; ?>"><b class="icon-pencil"></b>Edit Customer</a>
                                        <a class="btn btn-inverse pull-right" href="/admin/accounts/customer"><b class="icon-table"></b>Return to List</a>
                                    </div>
                                </div>
                                <div class="well">
<?php
echo $this->partial('admin/form-readonly-partial', array(
    'form'     => $this->form,
    'fieldset' => 'customerfieldset',
));
?>
                                </div>
                            </div>
                        </div>
                    </div>
