                    <h5 class="widget-name"><i class="icon-plus"></i>Create a New Subject</h5>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="widget">
                                <div class="navbar">
                                    <div class="navbar-inner"><h6><i class="icon-th-large"></i>Subject Details</h6></div>
                                </div>
                                <div class="well">
<?php
echo $this->partial('admin/form-partial', array(
    'form'     => $this->form,
    'url'      => '/admin/education/subjects/create',
    'fieldset' => 'subject-fieldset',
));
?>
                                </div>
                            </div>
                        </div>
                    </div>
