                    <h5 class="widget-name"><i class="icon-table"></i>View All Subjects</h5>
                    <div class="widget">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><i class="icon-th-large"></i>Subjects</h6>
                                <a class="btn btn-info pull-right" href="/admin/education/subjects/create"><b class="icon-plus"></b>Add New Subject</a>
                            </div>
                        </div>
                        <div class="table-overflow">
                            <table class="table table-striped table-bordered" id="data-table">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Disabled</th>
                                        <th class="actnCol">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->records as $record) { ?>
                                    <tr>
                                        <td><?php echo $record->getName(); ?></td>
                                        <td><?php echo ($record->getDisabled() ? 'Yes' : 'No'); ?></td>
                                        <td>
                                            <ul class="table-controls">
                                                <li><a href="/admin/education/subjects/edit/<?php echo $record->getSubjectId(); ?>" class="btn tip" title="Edit Record"><i class="icon-edit"></i> edit</a></li>
                                                <li><a href="/admin/education/subjects/view/<?php echo $record->getSubjectId(); ?>" class="btn tip" title="View Record"><i class="icon-external-link"></i> view</a></li>
                                                <li><a href="/admin/education/subjects/delete/<?php echo $record->getSubjectId(); ?>" class="btn tip confirm"><i class="icon-trash"></i> delete</a></li>
                                            </ul>
                                        </td>
                                    </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
