                    <h5 class="widget-name"><i class="icon-pencil"></i>Edit Emails</h5>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="widget">
                                <div class="navbar">
                                    <div class="navbar-inner">
                                        <h6><i class="icon-th-large"></i>Emails Details</h6>
                                    </div>
                                </div>
                                <div class="well">
<?php
echo $this->partial('admin/form-partial', array(
    'form'     => $this->form,
    'url'      => '/admin/accounts/emails/edit/' . $this->recordId,
    'fieldset' => 'emails-fieldset',
));
?>                             </div>
                            </div>
                        </div>
                    </div>
