<?php
$form = $this->form;
$form->setAttributes(array(
    'action' => '/about-us/drivers-council',
    'method' => 'POST',
    'id'     => 'forms',
))->prepare();
$fieldset = $form->getBaseFieldset();
$errors = $this->formElementErrors()
            ->setMessageOpenFormat('<span class="help-block">')
            ->setMessageSeparatorString('</span><span class="help-block">')
            ->setMessageCloseString('</span>');
?>
                <div id="dc_hero_header" class="col1">
                    <h1>Join Our<br>Drivers Council<br><span>and</span> Become Our<br>Ambassador</h1>
                </div>
                <div class="dc-left">
                    <h1 class="dc_callout">Are you an AVS or LUND FAN?</h1>
                    <h2 class="dc_callout">Spread the Word and WIN FREE Prizes and Products.</h2>
                </div><!-- end col2 -->
                <div class="dc-right">
                    <img alt="Like Us On Facebook!" src="/assets/application/lundinternational/images/fb_like_coa.png">
                </div>
                <div class="coll">
                    <article>
                        <p>At Lund International, we're dedicated to innovating products that are functional, high-performance, protective and stylish. We understand you're passionate about your "ride" and purchase our products for a variety of reasons. And, we're always trying to find new ways to better serve you and spread the word about the advantages our products can bring to drivers of all vehicle types.</p>
                        <h3 class="dc_callout">Share & Win!</h3>
                        <p>As a Drivers Council Member and Ambassador, you'll be able to share product advantages, product introductions, promotions, photos and videos about your vehicle and "road trip" stories with our social network and yours!</p>
                        <div class="module-a">
                            <img class="module-headerimg" alt="AVS-Lund-Drivers-Council-program" src="/assets/application/lundinternational/images/dc_woman.jpg"><br><br>
                            <h3 class="dc_callout">Show & Tell</h3>
                            <p>Most of us have a strong relationship with our ride - love or hate. Send us photos and a caption that best summarizes your relationship with your ride. Have any AVS or LUND products installed on your ride? We'll make sure your "show & tell" is highlighted on our Showroom page.</p>
                            <a style="font-size:12px;" href="/showroom"><strong>Show &amp; Tell your ride now! &raquo;</strong></a>
                        </div>
                    </article>
                </div>
                <div class="colr">
                    <div class="module-b">
                        <h3 style="width:100%;">You can participate as a Member of our Drivers Council in two ways:</h3>
                        <ol>
                            <li>Join as a Council Member and you'll be invited to share feedback, participate in surveys and receive a sign-up thank you product!</li>
                            <li>Join as a Drivers Council Brand Ambassador and you'll be invited to share feedback, participate in surveys, win FREE products and earn points to receive recognition and rewards by sharing news within your social network.</li>
                        </ol>
                        <div class="dc_left">
                            <h3>Membership Benefits</h3>
                            <ul class="simple">
                                <li>Share opinions on new product concepts</li>
                                <li>Complete short surveys guiding our market research</li>
                                <li>Test new product ideas</li>
                                <li>Promote new content, tips and resources within your network!</li>
                            </ul>
                            <p>As a Drivers Council Member and Ambassador, you will participate in all of the above PLUS be able to earn points to receive cool gear and a chance to win free AVS or LUND product each month.</p>
                        </div><!-- end dc_left -->
                        <div class="dc_right">
                            <div id="dc_text_callout">
                                <p>
                                    <strong>Share the word</strong><br>
                                    and you could win<br>
                                    <span>FREE</span><br>
                                    AVS and LUND<br>
                                    product each month<br>
                                </p>
                            </div><!-- end dc_text_callout -->
                        </div><!-- end dc_right -->
                        <figure id="dc-signup">
                            <h2 class="dc_signup">Sign Me Up!</h2>
                        </figure>
                        <div id="option1">
                            <h3 style="width:100%;">1. Yes, I Want to Become a Council Member</h3>
                            <?php if ($this->result == 'success') { ?>
                            <p>Thank you for signing up for the Lund International Drivers Council! An e-mail has been sent to you with more details. If you do not receive an e-mail within 1 hour, please e-mail <a href=mailto:info@lundinter.com>info@lundinter.com</a>.</p>
                            <p>The Lund International Marketing Team</p>
                            <?php } else { ?>
                            <p>Please join us by completing the form below:</p>
                                <?php if ($this->result == 'error') { ?>
                            <p style="color:#ff0000"><strong>There was an error processing your request.</strong></p>
                                <?php } ?>
                            <?php echo $this->form()->openTag($form); ?>
                            <?php echo $this->formElement($form->get('secret')); ?>
                            <input type="hidden" name="drivers-council-fieldset[disabled]" value="0" />
                            <input type="hidden" name="drivers-council-fieldset[site]" value="<?php echo $this->site->getSiteId(); ?>" />
                            <div class="formcolumn">
                                <?php $firstName = $fieldset->get('firstName'); ?>
                                <label><?php echo $firstName->getLabel() ?> *</label><?php echo $this->formElement($firstName); ?>
                                <?php $lastName = $fieldset->get('lastName'); ?>
                                <label><?php echo $lastName->getLabel() ?> *</label><?php echo $this->formElement($lastName); ?>
                                <?php $emailAddress = $fieldset->get('emailAddress'); ?>
                                <label><?php echo $emailAddress->getLabel() ?> *</label><?php echo $this->formElement($emailAddress); ?>
                                <?php $streetAddress = $fieldset->get('streetAddress'); ?>
                                <label><?php echo $streetAddress->getLabel() ?> *</label><?php echo $this->formElement($streetAddress); ?>
                            </div>
                            <div class="formcolumn">
                                <?php $locality = $fieldset->get('locality'); ?>
                                <label><?php echo $locality->getLabel() ?> *</label><?php echo $this->formElement($locality); ?>
                                <?php $region = $fieldset->get('region'); ?>
                                <label><?php echo $region->getLabel() ?> *</label><?php echo $this->formElement($region); ?>
                                <?php $postCode = $fieldset->get('postCode'); ?>
                                <label><?php echo $postCode->getLabel() ?> *</label><?php echo $this->formElement($postCode); ?>
                                <?php $country = $fieldset->get('country'); ?>
                                <label><?php echo $country->getLabel() ?> *</label><?php echo $this->formElement($country); ?>
                            </div>
                            <div id="checkboxes">
                                <textarea disabled="disabled">
Drivers Council Terms and Conditions
Last Modified on January 8, 2013

These terms and conditions govern the Lund International Drivers Council Program (the "Program"). Please take a moment to review these Program Terms and Conditions carefully. By using the Lund International Service, you agree to be bound by these Program terms and conditions.

ELIGIBILITY
All legal residents of the United States (including Puerto Rico) who are at least 18 years of age are eligible to participate in the Program. In order to participate in the Program, you should enroll with a valid first and last name, street address and e-mail address. Employees of Lund International, Inc. and its affiliates and partners, and each of their immediate family members and individuals living in the same households of each of these individuals, are eligible to participate in the Program, but these individuals may not participate in any sweepstakes or instant wins offered through the Program. We reserve the right to determine whether any particular user is eligible to participate in the Program.

ENROLLING IN THE PROGRAM
To enroll in the Program, please use the sign-up form found on the Lund International Drivers Council page, www.lundinternational.com/about-us/drivers-council. By doing so, you agree to provide Lund International with your correct first and last name, street address and e-mail address. Enrollment is free; there are no fees to enroll or participate in the Program at this time.

REWARDS
Upon enrollment, you will receive a complimentary sign-up gift for becoming a member of the Program. As a member of the Program, there may be opportunities at various times to qualify for prizes as incentives for your cooperation and membership.

COMMUNICATIONS
We may communicate with you regarding any matter related to the Program by email or by other communications, including mailings. All electronic communications to you sent from us, or on our behalf, will be deemed as communications "in writing".

CUSTOMER SERVICE
If you have a problem or question regarding your account, please contact the Lund International Drivers Council at driverscouncil@lundinter.com or Customer Service at info@lundinter.com. If you contact us regarding an error or mistake with respect to your account, we will use reasonable efforts to investigate and correct the error or mistake. All questions or disputes regarding the Program, including eligibility, obtaining credits, membership tiers, or redemption of credits for rewards, will be resolved by us in our sole discretion.

CHANGES TO THE PROGRAM
We may modify, restrict or change the Program and/or these Program Terms at any time. Changes may include, but are not limited to terms of eligibility and enrollment or type and selection of rewards. We will notify you of material changes to the Program and Program Terms and, unless you choose to terminate your Program participation, you will be bound by the revised Program Terms. Notification of material changes may be done through the email address you have provided to us, posting such changes on the Program web page, or by any other appropriate method, as we may determine. We also reserve the right to suspend or terminate the Program at any time, in our sole discretion, without liability or compensation to you.

ERROR PREVENTION AND OTHER ADJUSTMENTS
Occasionally, we may review the validity of your account, your actions and your compliance with these Program Terms.

TERMINATION OF YOUR PROGRAM MEMBERSHIP
You may cancel your membership at any time by notifying the Drivers Council at driverscouncil@lundinter.com or Customer Service at info@lundinter.com. Cancellation of your membership will be effective not later than thirty (30) days after you submit your request.

HOW TO CONTACT US
If you have any questions about this the Terms and Conditions, the practices of this service, or your dealings with this service, please contact us at driverscouncil@lundinter.com or Customer Service at info@lundinter.com, or: Lund International, Inc. 4325 Hamilton Mill road. Suite 400 Buford, GA 30518 1-888-588-6049
                                </textarea>
                                <?php $optin = $fieldset->get('optin'); ?>
                                <?php echo $this->formElement($optin); ?> 
                                <label>I Agree to Terms and Conditions</label>
                                <input class="btn btn-submit" type="submit" name="submit" value="Submit"> 
                            </div>
                            <?php echo $this->form()->closeTag($form); ?>
                            <?php } ?>
                        </div><!-- end option 1 -->
                        <figure id="dc-or">
                            <h3>or</h3>
                        </figure>
                        <div id="option2">
                            <h3 style="width:100%;">2. Yes, I Want to Become a Council Member<br>
                            and Brand Ambassador</h3>
                            <div id="toast_coa" style="cursor: pointer;">
                                <p>
                                    Spread the word about AVS and LUND with your friends to win FREE prizes and products!
                                    <!--<a class="btn-red" href="/about-us/drivers-council/brand-ambassador/">Sign Up</a>-->
                                </p>
                                <aside>
                                    <p>Help us promote on:</p>
                                    <img alt="Facebook and Twitter" src="/assets/application/lundinternational/images/socialhelp.png">
                                </aside>
                            </div><!-- end toast_coa -->
                        </div><!-- end option 2-->
                    </div><!-- end module-b -->
                    <div class="clear"></div>
                </div><!-- end colr -->
