<div class="colr">
<?php if ($this->type == 'list') { ?>
<img class="image-header" src="/assets/application/lundinternational/images/NewsHeader.jpg" />
<hr>
<?php 
if (is_array($this->news)) {
    $yearArray = array();

    foreach ($this->news as $news) {
        if (!array_key_exists($news->getDisplayDate()->format('Y'), $yearArray)) {
            $yearArray[$news->getDisplayDate()->format('Y')] = array();
        }

        $yearArray[$news->getDisplayDate()->format('Y')][] = array(
            'url'   => '/about-us/news/' . $news->getUrl() . '/' . urlencode($news->getTitle()),
            'date'  => $news->getDisplayDate(),
            'type'  => $news->getNewsType(),
            'title' => $news->getTitle());

    }

    krsort($yearArray);

    foreach ($yearArray as $record) {
        if ($record[0]['date']->format('Y') == date('Y')) {
            $heading = 'Latest News: ' . $record[0]['date']->format('Y');
        } else {
            $heading = 'News Archive: ' . $record[0]['date']->format('Y');
        }
?>
    <h1><?php echo $heading; ?></h1>
    <ul class="list-news">
<?php
    foreach ($record  as $news) {
?>
    <li><h2><a href="<?php echo $news['url']; ?>"<?php echo ($news['type'] == 'external' ? ' target="_blank"' : ''); ?>><?php echo $news['title']; ?></a></h2><strong><?php echo $news['date']->format('F j, Y'); ?></strong></li>
<?php
    }
?>
    </ul>
    <hr />
<?php
    }
}
?>
<?php } else { ?>
    <h1><?php echo $this->news->getTitle(); ?></h1>
    <h4><?php echo $this->news->getDisplayDate()->format('F j, Y'); ?></h4>
    <p><?php echo $this->news->getHtml(); ?></p>
    <p><a href="/about-us/news">&laquo; Back to News</a></p>
<?php } ?>
</div>
