<?php
$form = $this->form;
$form->setAttributes(array(
    'action' => '/customer-care/product-support',
    'method' => 'POST',
    'id'     => 'forms',
))->prepare();
$fieldset = $form->getBaseFieldset();
$errors = $this->formElementErrors()
            ->setMessageOpenFormat('<span class="help-block">')
            ->setMessageSeparatorString('</span><span class="help-block">')
            ->setMessageCloseString('</span>');
?>
                <div class="colr">
                    <h1>Get in touch with Lund International</h1>
                    <p>Have a question about Lund International or our products? Please contact us using the form below.<br>Note: For non-product support, please <a href="/contact">contact our main office</a></p> 
                    <?php if ($this->result == 'success') { ?>
                    <p>Thank you for contacting AVS and LUND! We appreciate your inquiry and our Customer Service specialists will get back to you within 24 hours. If you do not hear from our Customer Service department within 24 hours, please e-mail <a href="mailto:info@lundinter.com">info@lundinter.com</a>.</p>
                    <p>&nbsp;</p>
                    <p>&nbsp;</p>
                    <?php } else { ?>
                        <?php if ($this->result == 'error') { ?>
                    <p style="color:#ff0000"><strong>There was an error processing your request.</strong></p>
                        <?php } ?>
                    <?php echo $this->form()->openTag($form); ?>
                   <?php echo $this->formElement($form->get('secret')); ?>
                   <input type="hidden" name="support-request-fieldset[disabled]" value="0" />
                   <input type="hidden" name="support-request-fieldset[site]" value="<?php echo $this->site->getSiteId(); ?>" />
                   <div class="formcolumn">
                        <?php $firstName = $fieldset->get('firstName'); ?>
                        <label><?php echo $firstName->getLabel() ?> *</label><?php echo $this->formElement($firstName); ?>
                        <?php $lastName = $fieldset->get('lastName'); ?>
                        <label><?php echo $lastName->getLabel() ?> *</label><?php echo $this->formElement($lastName); ?>
                        <?php $emailAddress = $fieldset->get('emailAddress'); ?>
                        <label><?php echo $emailAddress->getLabel() ?> *</label><?php echo $this->formElement($emailAddress); ?>
                        <?php $phoneNumber = $fieldset->get('phoneNumber'); ?>
                        <label><?php echo $phoneNumber->getLabel() ?> *</label><?php echo $this->formElement($phoneNumber); ?>
                        <?php $streetAddress = $fieldset->get('streetAddress'); ?>
                        <label><?php echo $streetAddress->getLabel() ?> *</label><?php echo $this->formElement($streetAddress); ?>
                        <?php $locality = $fieldset->get('locality'); ?>
                        <label><?php echo $locality->getLabel() ?> *</label><?php echo $this->formElement($locality); ?>
                    </div>
                    <div class="formcolumn">
                        <?php $region = $fieldset->get('region'); ?>
                        <label><?php echo $region->getLabel() ?> *</label><?php echo $this->formElement($region); ?>
                        <?php $postCode = $fieldset->get('postCode'); ?>
                        <label><?php echo $postCode->getLabel() ?> *</label><?php echo $this->formElement($postCode); ?>
                        <?php $country = $fieldset->get('country'); ?>
                        <label><?php echo $country->getLabel() ?> *</label><?php echo $this->formElement($country); ?>
                        <?php $vehicle = $fieldset->get('vehicle'); ?>
                        <label><?php echo $vehicle->getLabel() ?> *</label><?php echo $this->formElement($vehicle); ?>
                        <?php $partNumber = $fieldset->get('partNumber'); ?>
                        <label><?php echo $partNumber->getLabel() ?> *</label><?php echo $this->formElement($partNumber); ?>
                        <?php $wherePurchase = $fieldset->get('wherePurchase'); ?>
                        <label><?php echo $wherePurchase->getLabel() ?> *</label><?php echo $this->formElement($wherePurchase); ?>
                    </div>
                    <div class="clear"></div>
                    <div class="formcolumn">
                        <?php $comments = $fieldset->get('comments'); ?>
                        <label><?php echo $comments->getLabel() ?> *</label><?php echo $this->formElement($comments); ?>
                    </div>
                    <div class="clear"></div>
                    <input id="supportrequestsub" class="btn btn-submit" type="submit" name="submit" value="Submit" />
                    <?php echo $this->form()->closeTag($form); ?>
                    <p>&nbsp;</p>
                    <?php } ?>
                </div>
