                <div class="brands">
                    <ul>
                        <li><a href="#"><img src="/assets/application/lundinternational/images/brand-AVS.png" /></a></li>
                        <li><a href="#"><img src="/assets/application/lundinternational/images/brand-LUND.png" /></a></li>
                        <li><a href="http://belmor.com/" target="_blank"><img src="/assets/application/lundinternational/images/brand-Belmor.png" /></a></li>
                        <li><a href="http://amp-research.com" target="_blank"><img src="/assets/application/lundinternational/images/brand-AMP.png" /></a></li>
                    </ul>
                </div>
                <div class="col-full-portal">
                    <div class="left">
                        <article>
                            <h1 class="portal">Welcome.</h1>
                            <p class="bold_gray">User: <?php echo $user->getFirstName(); ?> <?php echo $user->getLastName(); ?> / <a class="redLink" href="/logout">logout</a></p>
                        </article>
                    </div>
                    <div class="right">
                    	<article>
	                    	<div class="module-h">
                             	<p class="bold_gray"><span class="red_headline">User Profile</span></p>
                                	<ul class="bold_gray" style="padding-bottom:40px;">
                                        <li>Name:<span class="profile_info"><?php echo $user->getFirstName(); ?> <?php echo $user->getLastName(); ?></span></li>
                                        <li>Email Address:<span class="profile_info"><?php echo $user->getEmailAddress(); ?></span></li>
                                        <li>Address:<span class="profile_info"><?php echo $user->getStreetAddress(); ?><br /><?php echo $user->getLocality(); ?>, <?php echo $user->getRegion()->getSubdivisionName(); ?> <?php echo $user->getPostCode(); ?></span></li>
                                   	</ul>
                                </div>
                       </article>
                    </div>
                    <div class="clear"></div>
                    <table class="portal-table">
                        <thead>
                            <tr>
                                <td colspan="6">Online Orders</td>
                            </tr>
                        </thead>
                        <tr>
                            <th>Created</th>
                            <th>Order ID</th>
                            <th>Total</th>
                            <th>Products</th>
                            <th>Shipping Address</th>
                            <th>Shipping Method</th>
                        </tr>
                        <?php foreach ($orders as $order) { ?>
                            <?php $orderItems = $orderItemService->getOrderItemsByOrder($order); ?>
                        <tr>
                            <td data-title="Created"><?php echo $order->getCreatedAt()->format('m/d/Y'); ?></td>
                            <td data-title="Order ID"><?php echo $order->getOrderId(); ?></td>
                            <td data-title="Total">$<?php echo $order->getTotal(); ?></td>
                            <td data-title="Products" style="text-align:left;padding-left:7px;">
                                <?php foreach ($orderItems as $item) { ?>
                                <strong>Description:</strong> <?php echo $item->getDescription(); ?><br />
                                <strong>Quantity:</strong> <?php echo $item->getQuantity(); ?><br />
                                <strong>Price:</strong> $<?php echo $item->getPrice(); ?><br />
                                <?php } ?>
                            </td>
                            <td data-title="Shipping Address">
                                <?php echo $order->getShippingAddress()->getStreetAddress(); ?><br />
                                <?php echo ($order->getShippingAddress()->getExtStreetAddress() ? $order->getShippingAddress()->getExtStreetAddress() . '<br/>' : ''); ?>
                                <?php echo $order->getShippingAddress()->getLocality(); ?>, <?php echo $order->getShippingAddress()->getRegion()->getSubdivisionName(); ?> <?php echo $order->getShippingAddress()->getPostCode(); ?>
                            </td>
                            <td data-title="Shipping Method"><?php echo $order->getShippingMethod()->getLabel(); ?></td>
                        </tr>
                        <?php } ?>
                    </table>
                </div>
