		<!-- end-unit -->
	    <div class="end-unit">
	    	<hr/>
			<h7>&copy; Copyright <?php echo date("Y") ?>, Averitt Express, Inc.
			<br/><a href="http://www.averittexpress.com/privacy-policy" target="_blank">Privacy Policy</a></h7>
		</div>
		<!-- end end-unit -->
	</div>
	<!-- end container -->
	<!--AppCast Job View Pixel-->
	<script type="text/javascript">
	(function() { var ac = document.createElement('script'); ac.type = 'text/javascript'; ac.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'pixel.app-cast.com/pixels/transportation1-149.js?t=1393961195'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ac, s); })();
	</script>
	<!--End AppCast Job View Pixel-->
	<?php echo $this->inlineScript() ?>
	</body>
</html>