<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">
    <head>
        <title><?php echo (null !== $this->metaTitle ? $this->metaTitle : 'Lund International | AVS | LUND'); ?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel="profile" href="http://gmpg.org/xfn/11" />
        <meta name="viewport" content="initial-scale=1, maximum-scale=1" />
        <meta name="viewport" content="width=device-width" />
        <meta name="keywords" content="<?php echo (null !== $this->metaKeywords ? $this->metaKeywords : 'Lund International'); ?>" />
        <meta name="description" content="<?php echo (null !== $this->metaDescription ? $this->metaDescription : 'Lund is a trusted brand name offering premium accessories that are stylish, functional and durable. From running boards to tonneaus, window vents to grilles and hood shields to cargo management.'); ?>" />
        <meta name="google-site-verification"  content="4qrzZjtioVCerbcJlLwhZRALckxKjCjTdCra4Ul7cVo" />
        <meta name="google-site-verification" content="C488ho40XJ2O-II9xXhvm0jTzQGFko6ScBvmj5AP9LM" />
        <meta name="p:domain_verify" content="b1eb3cc8325ab3fc123003dce95a6c84"/>
        <link rel="stylesheet" href="http://staging.group1201.com/averittdrivers/positions/_assets/css/style.css">
        <link rel="stylesheet" href="/assets/application/averittdrivers/css/resp.min.css">
		<link rel="stylesheet" href="/assets/application/averittdrivers/css/resp-responsive.css">
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
            <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
            <style type="text/css">.brands{filter: none;}</style>
        <![endif]-->
        <style>
			body {
			    background-color: #f4f4f4;
			    color:black;
			}
		</style>
        <!-- Start Google Analytics Tracking -->
        <script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-13033333-1']);
		  _gaq.push(['_trackPageview']);
		  _gaq.push(['t2._setAccount', 'UA-34267514-1']);
		  _gaq.push(['t2._trackPageview']);
		
		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();
		
		</script>
        <!-- End Google Analytics Tracking -->
    </head>
		<!-- container -->         
		<div class="container">
        
