<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'smart-accounts/customer/create' => __DIR__ . '/view/smart-accounts/customer/create.phtml',
    'smart-accounts/customer/edit'   => __DIR__ . '/view/smart-accounts/customer/edit.phtml',
    'smart-accounts/customer/index'  => __DIR__ . '/view/smart-accounts/customer/index.phtml',
    'smart-accounts/customer/view'   => __DIR__ . '/view/smart-accounts/customer/view.phtml',
);
