<style>
#summaries .formcolumn:first-of-type {
    margin-right: 2%;
}
#summaries .formcolumn {
    float: left;
    width: 49%;
}
.alignleft h1 {font-weight:bold; font-size:22px;}
.btn-smr {background: rgb(107,107,107); /* Old browsers */
background: -moz-linear-gradient(top,  rgba(107,107,107,1) 2%, rgba(17,17,17,1) 47%, rgba(43,43,43,1) 76%, rgba(28,28,28,1) 91%, rgba(19,19,19,1) 100%); /* FF3.6+ */
background: -webkit-gradient(linear, left top, left bottom, color-stop(2%,rgba(107,107,107,1)), color-stop(47%,rgba(17,17,17,1)), color-stop(76%,rgba(43,43,43,1)), color-stop(91%,rgba(28,28,28,1)), color-stop(100%,rgba(19,19,19,1))); /* Chrome,Safari4+ */
background: -webkit-linear-gradient(top,  rgba(107,107,107,1) 2%,rgba(17,17,17,1) 47%,rgba(43,43,43,1) 76%,rgba(28,28,28,1) 91%,rgba(19,19,19,1) 100%); /* Chrome10+,Safari5.1+ */
background: -o-linear-gradient(top,  rgba(107,107,107,1) 2%,rgba(17,17,17,1) 47%,rgba(43,43,43,1) 76%,rgba(28,28,28,1) 91%,rgba(19,19,19,1) 100%); /* Opera 11.10+ */
background: -ms-linear-gradient(top,  rgba(107,107,107,1) 2%,rgba(17,17,17,1) 47%,rgba(43,43,43,1) 76%,rgba(28,28,28,1) 91%,rgba(19,19,19,1) 100%); /* IE10+ */
background: linear-gradient(to bottom,  rgba(107,107,107,1) 2%,rgba(17,17,17,1) 47%,rgba(43,43,43,1) 76%,rgba(28,28,28,1) 91%,rgba(19,19,19,1) 100%); /* W3C */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#6b6b6b', endColorstr='#131313',GradientType=0 ); /* IE6-9 */
border-radius:7px;
padding:5px 10px;
color:#fff;
text-transform:uppercase;
font-weight:bold;
font-size:12px;
}
#forms input{width:40%;}
#forms label{display:block;}
#forms .formcolumn select,
.module-b #forms select{width:40%;}
.cart-inner {float:left; width:100%;background: rgb(255,255,255); /* Old browsers */
background: -moz-linear-gradient(top,  rgba(255,255,255,1) 0%, rgba(252,252,252,1) 38%, rgba(229,229,229,1) 100%); /* FF3.6+ */
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(255,255,255,1)), color-stop(38%,rgba(252,252,252,1)), color-stop(100%,rgba(229,229,229,1))); /* Chrome,Safari4+ */
background: -webkit-linear-gradient(top,  rgba(255,255,255,1) 0%,rgba(252,252,252,1) 38%,rgba(229,229,229,1) 100%); /* Chrome10+,Safari5.1+ */
background: -o-linear-gradient(top,  rgba(255,255,255,1) 0%,rgba(252,252,252,1) 38%,rgba(229,229,229,1) 100%); /* Opera 11.10+ */
background: -ms-linear-gradient(top,  rgba(255,255,255,1) 0%,rgba(252,252,252,1) 38%,rgba(229,229,229,1) 100%); /* IE10+ */
background: linear-gradient(to bottom,  rgba(255,255,255,1) 0%,rgba(252,252,252,1) 38%,rgba(229,229,229,1) 100%); /* W3C */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#e5e5e5',GradientType=0 ); /* IE6-9 */
border:1px solid #e5e5e5;
height:30px;
margin:10px 0;}
.cart-inner li {
float:left;
position:relative;
margin:0 auto;
padding:5px 0 0 10px;
font-weight:bold;
}
.cart-inner li:first-child {width:58%; padding-left:40px;}
.cart-inner li:nth-child(2) {width:10%;}
.cart-inner li:nth-child(3) {width:14%;}
.cart-inner li:nth-child(4) {width:10%;}
.cart-details {float:left; width:100%;border-bottom:1px solid #000; padding-bottom:15px;}
.cart-details li {float:left; padding:5px 0 0 15px;}
.cart-details li:first-child {width:58%; padding-left:40px;}
.cart-details li:nth-child(2) {width:10%;}
.cart-details li:nth-child(3) {width:14%; padding-left:5px;}
.cart-details li:nth-child(4) {width:8%;}
.quantity {width:5px; padding:5px 15px 3px 5px;}
.product-name sup {background:#ccc;border-radius:50%;color:#000;padding:1px 4px;cursor:pointer;margin-right:10px;}
.totals {margin-bottom:15px;}
.totals li {width:190px; line-height:28px;text-align:right;}
.totals li span {text-align:right; width:42%; float:right;}
.grand {font-size:18px; font-weight:bold;}
.checkout {font-size:14px; margin-bottom:20px;}
.checkout-holder div:first-child {width:72%; margin-top:20px;padding-left:20px;}
.checkout-holder div:nth-child(2) {width:25%; margin-top:20px;}
.checkout-holder div input {margin-bottom:10px;height:19px;}
.checkout-holder div p {font-size:14px; font-weight:bold; margin-bottom:15px;}
@media only screen and (max-width:1100px) {
    .cart-inner li:first-child, .cart-details li:first-child {width:50%;}
    .checkout-holder div:first-child  {width:60%;}
    .checkout-holder div:nth-child(2) {width:35%;}
}
@media only screen and (max-width:979px) {

}
@media only screen and (max-width:759px) {
    .cart-inner li:first-child, .cart-details li:first-child {width:30%;padding-left:30px;}
    .cart-inner li:nth-child(2), .cart-details li:nth-child(2) {width:18%;}
    .checkout-holder {-webkit-flex-direction: column-reverse; flex-direction:column-reverse;}
    .checkout-holder div:first-child  {width:58%;-webkit-align-self:flex-end; align-self:flex-end; margin-bottom:15px; }
    .checkout-holder div:nth-child(2) {width:57%; -webkit-align-self:flex-end; align-self:flex-end;}
}
@media only screen and (max-width:479px) {
    .col-full .alignleft {float:none;}
    .col-full .alignright {float:none;}
    .cart-inner li:first-child, .cart-details li:first-child {padding-left:10px; width:20%;}
    .cart-inner li:nth-child(2), .cart-details li:nth-child(2){width:24%;}
    .product-name sup {margin-right:0;}
    .checkout-holder div:first-child  {width:80%;-webkit-align-self:flex-end; align-self:flex-end; margin-bottom:15px; }
    .checkout-holder div:nth-child(2) {width:83%; -webkit-align-self:flex-end; align-self:flex-end;}
}
</style>
<?php
$form = $this->form;
if ($this->step == 'billing') {
    $action = 'shipping';
} else if ($this->step == 'shipping') {
    $action = 'payment';
} else if ($this->step == 'payment') {
    $action = 'confirmation';
} else if ($this->step == 'confirmation') {
    $action = 'process';
}
if ($form) {
    $form->setAttributes(array(
        'action' => '/checkout/' . $action,
        'method' => 'POST',
        'id'     => 'forms',
    ))->prepare();
    $fieldset = $form->getBaseFieldset();
    $errors = $this->formElementErrors()
                ->setMessageOpenFormat('<span class="help-block">')
                ->setMessageSeparatorString('</span><span class="help-block">')
                ->setMessageCloseString('</span>');
}
?>
                <div class="col-full">
                    <div class="alignleft">
                        <h1 class="fgd">Order Checkout</h1>
                    </div>
                    <?php if ($form){ ?>
                    <div class="alignright">
                        <a href="/cart" class="btn-smr btn-continue-shop"><span>Return to Cart</span></a></h1>
                        <a href="/products" class="btn-smr btn-continue-shop"><span>Continue Shopping</span></a></h1>
                    </div>
                    <div class="clear"></div>
                    <div class="module-b" style="margin-top:25px;">
                        <?php echo $this->form()->openTag($form); ?>
                        <?php echo $this->formElement($form->get('secret')); ?>
                        <?php } ?>
                        <?php if ($this->step == 'billing') { ?>
                        <input type="hidden" name="order-address-fieldset[disabled]" value="0" />
                        <input type="hidden" name="order-address-fieldset[addressType]" value="billing" />
                        <div class="formColumn">
                            <h1 class="title">Billing Address</h1>
                            <?php $firstName = $fieldset->get('firstName'); ?>
                            <label><?php echo $firstName->getLabel(); ?></label><?php echo $this->formElement($firstName); ?>
                            <?php $lastName = $fieldset->get('lastName'); ?>
                            <label><?php echo $lastName->getLabel(); ?></label><?php echo $this->formElement($lastName); ?>
                            <?php $phoneNumber = $fieldset->get('phoneNumber'); ?>
                            <label><?php echo $phoneNumber->getLabel(); ?></label><?php echo $this->formElement($phoneNumber); ?>
                            <?php $streetAddress = $fieldset->get('streetAddress'); ?>
                            <label><?php echo $streetAddress->getLabel(); ?></label><?php echo $this->formElement($streetAddress); ?>
                            <?php $extStreetAddress = $fieldset->get('extStreetAddress'); ?>
                            <label><?php echo $extStreetAddress->getLabel(); ?></label><?php echo $this->formElement($extStreetAddress); ?>
                            <?php $locality = $fieldset->get('locality'); ?>
                            <label>City</label><?php echo $this->formElement($locality); ?>
                            <?php $region = $fieldset->get('region'); ?>
                            <label>State</label><?php echo $this->formElement($region); ?>
                            <?php $postCode = $fieldset->get('postCode'); ?>
                            <label><?php echo $postCode->getLabel(); ?></label><?php echo $this->formElement($postCode); ?>
                            <?php $country = $fieldset->get('country'); ?>
                            <label><?php echo $country->getLabel(); ?></label><?php echo $this->formElement($country); ?>
                        </div>
                        <div class="clear"></div>
                        <input id="submitBillingAddress" class="btn btn-submit" type="submit" name="submit" value="Submit" />
                        <?php } else if ($this->step == 'shipping') { ?>
                        <input type="hidden" name="order-address-fieldset[disabled]" value="0" />
                        <input type="hidden" name="order-address-fieldset[addressType]" value="shipping" />
                        <div class="form-row">
                            <input type="checkbox" name="sameasbilling" id="sameasbilling" value="1" /> <label>Same as billing information</label>
                        </div>
                        <div class="formColumn">
                            <h1 class="title">Shipping Address</h1>
                            <?php $firstName = $fieldset->get('firstName'); ?>
                            <label><?php echo $firstName->getLabel(); ?></label><?php echo $this->formElement($firstName); ?>
                            <?php $lastName = $fieldset->get('lastName'); ?>
                            <label><?php echo $lastName->getLabel(); ?></label><?php echo $this->formElement($lastName); ?>
                            <?php $phoneNumber = $fieldset->get('phoneNumber'); ?>
                            <label><?php echo $phoneNumber->getLabel(); ?></label><?php echo $this->formElement($phoneNumber); ?>
                            <?php $streetAddress = $fieldset->get('streetAddress'); ?>
                            <label><?php echo $streetAddress->getLabel(); ?></label><?php echo $this->formElement($streetAddress); ?>
                            <?php $extStreetAddress = $fieldset->get('extStreetAddress'); ?>
                            <label><?php echo $extStreetAddress->getLabel(); ?></label><?php echo $this->formElement($extStreetAddress); ?>
                            <?php $locality = $fieldset->get('locality'); ?>
                            <label>City</label><?php echo $this->formElement($locality); ?>
                            <?php $region = $fieldset->get('region'); ?>
                            <label>State</label><?php echo $this->formElement($region); ?>
                            <?php $postCode = $fieldset->get('postCode'); ?>
                            <label><?php echo $postCode->getLabel(); ?></label><?php echo $this->formElement($postCode); ?>
                            <?php $country = $fieldset->get('country'); ?>
                            <label><?php echo $country->getLabel(); ?></label><?php echo $this->formElement($country); ?>
                        </div>
                        <div class="clear"></div>
                        <input id="submitShippingAddress" class="btn btn-submit" type="submit" name="submit" value="Submit" />
                        <?php } else if ($this->step == 'payment') { ?>
                        <input type="hidden" name="order-fieldset[disabled]" value="0" />
                        <div class="formColumn">
                            <h1 class="title">Shipping Method</h1>
                            <?php $shippingMethod = $fieldset->get('shippingMethod'); ?>
                            <label><?php echo $shippingMethod->getLabel(); ?></label><?php echo $this->formElement($shippingMethod); ?>
                            <h1 class="title">Payment Information</h1>
                            <?php $emailAddress = $fieldset->get('emailAddress'); ?>
                            <label><?php echo $emailAddress->getLabel(); ?></label><?php echo $this->formElement($emailAddress); ?>
                            <?php $cardType = $fieldset->get('cardType'); ?>
                            <label><?php echo $cardType->getLabel(); ?></label><?php echo $this->formElement($cardType); ?>
                            <?php $cardName = $fieldset->get('cardName'); ?>
                            <label><?php echo $cardName->getLabel(); ?></label><?php echo $this->formElement($cardName); ?>
                            <?php $cardNumber = $fieldset->get('cardNumber'); ?>
                            <label><?php echo $cardNumber->getLabel(); ?></label><?php echo $this->formElement($cardNumber); ?>
                            <?php $cardExpMonth = $fieldset->get('cardExpMonth'); ?>
                            <label><?php echo $cardExpMonth->getLabel(); ?></label><?php echo $this->formElement($cardExpMonth); ?>
                            <?php $cardExpYear = $fieldset->get('cardExpYear'); ?>
                            <label><?php echo $cardExpYear->getLabel(); ?></label><?php echo $this->formElement($cardExpYear); ?>
                            <?php $cardCvv = $fieldset->get('cardCvv'); ?>
                            <label><?php echo $cardCvv->getLabel(); ?></label><?php echo $this->formElement($cardCvv); ?>
                        </div>
                        <div class="clear"></div>
                        <input id="submitPayment" class="btn btn-submit" type="submit" name="submit" value="Submit" />
                        <?php } else if ($this->step == 'confirmation') { ?>
                    <div class="clear"></div>
                    <ul class="cart-inner">
                        <li>Product</li>
                        <li>Unit Price</li>
                        <li>Qty.</li>
                        <li>Subtotal</li>
                    </ul>
                    <?php
                        $orderItems = $this->orderItemService->getOrderItemsByOrder($this->order);
                    ?>
                    <?php foreach($orderItems as $item) { ?>
                    <ul class="cart-details">
                        <li class="product-name"><?php echo $item->getDescription(); ?></li>
                        <li>$<?php echo $item->getPrice(); ?></li>
                        <li><?php echo $item->getQuantity(); ?></li>
                        <li>$<?php echo ($item->getQuantity() * $item->getPrice()); ?></li>
                    </ul>
                    <?php } ?>
                    <div class="clear"></div>
                    <div class="checkout-holder">
                        <div style="display:none;">
                            <p>If you have a discount code, enter it here:</p>
                            <input type="text" name="discount-code"><br>
                            <a class="btn-smr">Apply Discount</a>
                        </div>
                        <div class="alignright">
                            <ul class="totals">
                                <li>Subtotal <span class="price">$<?php echo $this->order->getSubtotal(); ?></span></li>
                                <li>Shipping <span class="shipping">$<?php echo $this->order->getShippingCost(); ?></span></li>
                                <li>Tax <span class="price">$<?php echo $this->order->getTaxCost(); ?></span></li>
                                <li class="grand">Grand Total <span>$<?php echo $this->order->getTotal(); ?></span></li>
                            </ul>
                        </div>
                    </div>
                    <div style="clear:both;"></div>
                    <div id="summaries" class="module-b" style="margin-top:25px;">
                        <h1 class="title">Order Summary</h1>
                        <div class="formcolumn">
                            <h2>Billing Address</h2>
                            <p>
                                First Name: <?php echo $this->order->getBillingAddress()->getFirstName(); ?><br />
                                Last Name: <?php echo $this->order->getBillingAddress()->getLastName(); ?><br />
                                Street Address: <?php echo $this->order->getBillingAddress()->getStreetAddress(); ?><br />
                                Extended Street Address: <?php echo $this->order->getBillingAddress()->getExtStreetAddress(); ?><br />
                                City: <?php echo $this->order->getBillingAddress()->getLocality(); ?><br />
                                State: <?php echo $this->order->getBillingAddress()->getRegion()->getSubdivisionName(); ?><br />
                                Post Code: <?php echo $this->order->getBillingAddress()->getPostCode(); ?><br />
                                Country: <?php echo $this->order->getBillingAddress()->getCountry()->getName(); ?><br />
                                Phone Number: <?php echo $this->order->getBillingAddress()->getPhoneNumber(); ?><br />
                            </p>
                            <h2>Payment Information</h2>
                            <p>
                                Credit Card Type: <?php echo $this->order->getCardType(); ?><br />
                                Name on Card: <?php echo $this->order->getCardName(); ?><br />
                                Card Number: <?php echo str_repeat("X", strlen($this->order->getCardNumber()) - 4) . substr($this->order->getCardNumber(), -4); ?><br />
                                Card Expiration: <?php echo $this->order->getCardExpMonth(); ?>/<?php echo $this->order->getCardExpYear(); ?><br />
                                Card CVV: <em>Hidden for security purposes</em><br />
                            </p>
                        </div>
                        <div class="formcolumn">
                            <h2>Shipping Address</h2>
                             <p>
                                First Name: <?php echo $this->order->getShippingAddress()->getFirstName(); ?><br />
                                Last Name: <?php echo $this->order->getShippingAddress()->getLastName(); ?><br />
                                Street Address: <?php echo $this->order->getShippingAddress()->getStreetAddress(); ?><br />
                                Extended Street Address: <?php echo $this->order->getShippingAddress()->getExtStreetAddress(); ?><br />
                                City: <?php echo $this->order->getShippingAddress()->getLocality(); ?><br />
                                State: <?php echo $this->order->getShippingAddress()->getRegion()->getSubdivisionName(); ?><br />
                                Post Code: <?php echo $this->order->getShippingAddress()->getPostCode(); ?><br />
                                Country: <?php echo $this->order->getShippingAddress()->getCountry()->getName(); ?><br />
                                Phone Number: <?php echo $this->order->getShippingAddress()->getPhoneNumber(); ?><br />
                            </p>
                            <h2>Shipping Method</h2>
                            <p>
                                Method: <?php echo $this->order->getShippingMethod()->getLabel(); ?><br />
                            </p>
                        </div>
                        <div class="clear"></div>
                        <div class="formcolumn">
                            <a href="/checkout/process" class="btn-red">Proceed with Checkout</a>
                        </div>
                        <div class="clear"></div>
                        <p>&nbsp;</p>
                    </div>
                        <?php } else if ($this->step == 'process') { ?>
                    <div class="clear"></div>
                    <div class="module-b" style="margin-top:25px;">
                        <h1 class="title">Thanks for your order!</h1>
                        <p>You should receive an email confirmation soon. Thanks for shopping with Lund International!</p>
                    </div>
                        <?php } ?>
                        <?php if ($form) { ?>
                        <?php echo $this->form()->closeTag($form); ?>
                        <?php } ?>
                    <?php if ($form) { ?>
                    </div>
                    <?php } ?>
                </div>
                <?php if ($this->step == 'shipping') { ?>
                    <?php $billingAddress = $this->order->getBillingAddress(); ?>
                <script type="text/javascript" language="javascript">
                    $(function() {
                        $('#sameasbilling').click(function(){
                            if ($(this).is(':checked')) {
                                $('input[name="order-address-fieldset[firstName]"]').val('<?php echo $billingAddress->getFirstName(); ?>');
                                $('input[name="order-address-fieldset[lastName]"]').val('<?php echo $billingAddress->getLastName(); ?>');
                                $('input[name="order-address-fieldset[phoneNumber]"]').val('<?php echo $billingAddress->getPhoneNumber(); ?>');
                                $('input[name="order-address-fieldset[streetAddress]"]').val('<?php echo $billingAddress->getStreetAddress(); ?>');
                                $('input[name="order-address-fieldset[extStreetAddress]"]').val('<?php echo $billingAddress->getExtStreetAddress(); ?>');
                                $('input[name="order-address-fieldset[locality]"]').val('<?php echo $billingAddress->getLocality(); ?>');
                                $('select[name="order-address-fieldset[region]"]').val('<?php echo $billingAddress->getRegion()->getStateId(); ?>');
                                $('input[name="order-address-fieldset[postCode]"]').val('<?php echo $billingAddress->getPostCode(); ?>');
                                $('select[name="order-address-fieldset[country]"]').val('<?php echo $billingAddress->getCountry()->getCountryId(); ?>');
                            }
                        });
                    });
                </script>
                <?php } ?>
