<?php
$form = $this->form;
$form->setAttributes(array(
    'action' => '/login',
    'method' => 'POST',
))->prepare();
$fieldset = $form->getBaseFieldset();
$errors = $this->formElementErrors()
            ->setMessageOpenFormat('<span class="help-block">')
            ->setMessageSeparatorString('</span><span class="help-block">')
            ->setMessageCloseString('</span>');
?>
                <div class="brands">
                    <ul>
                        <li><a href="#"><img src="/assets/application/lundinternational/images/brand-AVS.png" /></a></li>
                        <li><a href="#"><img src="/assets/application/lundinternational/images/brand-LUND.png" /></a></li>
                        <li><a href="http://belmor.com/" target="_blank"><img src="/assets/application/lundinternational/images/brand-Belmor.png" /></a></li>
                        <li><a href="http://amp-research.com" target="_blank"><img src="/assets/application/lundinternational/images/brand-AMP.png" /></a></li>
                    </ul>
                </div>
                <div class="col-full-login">
                    <div class="coll">
                        <article class="module-c">
                            <h2 class="login">Please sign in to continue</h2>
                            <?php echo $this->form()->openTag($form); ?>
                            <input type="hidden" name="login-fieldset[rememberme]" value="1" />
                            <?php $username = $fieldset->get('username'); ?>
                            <label><?php echo $username->getLabel(); ?></label>
                            <?php echo $this->formElement($username); ?>
                            <?php $password = $fieldset->get('password'); ?>
                            <label><?php echo $password->getLabel(); ?></label>
                            <?php echo $this->formElement($password); ?>
                            <br>
                            <input type="submit" name="login" value="Login">
                            <?php echo $this->form()->closeTag($form); ?>
                        </article>
                    </div>
                </div>
