                <script type="text/javascript">
                    $(function(){
                        var elfinder = $('#file-manager').elfinder({
                            url: '/portal/connector'
                        });
                    });
                </script> 
                <div class="brands">
                    <ul>
                        <li><a href="#"><img src="/assets/application/lundinternational/images/brand-AVS.png" /></a></li>
                        <li><a href="#"><img src="/assets/application/lundinternational/images/brand-LUND.png" /></a></li>
                        <li><a href="http://belmor.com/" target="_blank"><img src="/assets/application/lundinternational/images/brand-Belmor.png" /></a></li>
                        <li><a href="http://amp-research.com" target="_blank"><img src="/assets/application/lundinternational/images/brand-AMP.png" /></a></li>
                    </ul>
                </div>
                <div class="col-full-portal">
                    <div class="left">
                        <article>
                            <h1 class="portal">Welcome.</h1>
                            <p class="bold_gray">Customer: <?php echo $customer->getContactName(); ?> / <a class="redLink" href="/logout">logout</a></p>
                            <p>Questions or to make changes email <a href="mailto:pims@lundinter.com" class="redLink">pims@lundinter.com</a>.</p>
                        </article>
                    </div>
                    <div class="right">
                    	<article>
	                    	<div class="module-h">
                             	<p class="bold_gray"><span class="red_headline">Customer Profile</span></p>
                                	<ul class="bold_gray">
                                        <li>Company Name:<span class="profile_info"><?php echo $customer->getName(); ?></span></li>
                                        <li>Contact Name:<span class="profile_info"><?php echo $customer->getContactName(); ?></span></li>
                                        <li>Email Address:<span class="profile_info"><?php echo $customer->getEmail(); ?></span></li>
                                   	</ul>
                                </div>
                       </article>
                    </div>
                    <div class="clear"></div>
                    <table class="portal-table">
                    	<tr>
                        	<th>TX Method:</th>
                            <th>FTP Information:</th>
                            <th>Last Update:</th>
                            <th>Update Type:</th>
                            <th>Frequency</th>
                        </tr>
                        <tr>
                        	<td data-title="TX Method"><?php echo ($customer->getFilePickup() ? 'Pickup File' : 'Push File'); ?></td>
                            <td data-title="FTP Information"><?php echo ($customer->getFtpSite() ? $customer->getFtpSite() . ' (' . $customer->getFtpUser() . '/******)' : 'N/A'); ?></td>
                            <td data-title="Last Update"><?php echo ($customer->getLastUpdate() ? $customer->getLastUpdate()->format('Y-m-d') : 'Unknown'); ?></td>
                            <td data-title="Update Type"><?php echo ($customer->getUpdateType() == 'net' ? 'Net Change' : 'Full'); ?></td>
                            <td data-title="Frequency"><?php echo ($customer->getFrequency() == 'week' ? 'Weekly' : 'Monthly'); ?></td>
                        </tr>
                    </table> 
                    <?php 
                    if ($this->changesets) { 
                        foreach ($this->changesets as $changeset) {
                            if ($changeset->getDeployed()) {
                    ?>
                    <table class="portal-table">
                    	<thead>
                        	<tr>
                                <td colspan="4">Changeset <?php echo $changeset->getCreatedAt()->format('m/d/Y @ g:ia'); ?></td>
                            </tr>
                        </thead>
                        <tr>
                        	<th>Type</th>
                            <th>Brand</th>
                            <th>Format</th>
                            <th>Download</th>
                        </tr>
                                <?php 
                                $files = $this->fileLogService->getFileLogByChangeset($changeset);
                                if (null != $files) {
                                    foreach ($files as $file) {
                                        if ($file->getBrand() == 'BELMOR') { continue; }
                                        if ($customer->getUpdateType() == 'net' && ($file->getType() == 'master' || $file->getType() == 'aces-incr' || $file->getType() == 'pies-incr-xml' || $file->getType() == 'pies-incr-csv' || $file->getType() == 'assetpackage')) {
                                            if ($file->getType() == 'aces-incr' && $customer->getAcesVersion() == 'FLAT') {
                                                continue;
                                            } elseif ($file->getType() == 'master' && $customer->getAcesVersion() != 'FLAT') {
                                                continue;
                                            } elseif ($file->getType() == 'pies-incr-xml' && $customer->getPiesVersion() == 'FLAT') {
                                                continue;
                                            } elseif ($file->getType() == 'pies-incr-csv' && $customer->getPiesVersion() != 'FLAT') {
                                                continue;
                                            }

                                            if ($file->getBrand() == 'AVS' && !$customer->getAvs()) {
                                                continue;
                                            } elseif ($file->getBrand() == 'LUNDONLY' && !$customer->getLund()) {
                                                continue;
                                            } elseif ($file->getbrand() == 'LUND' && !$customer->getLundAll()) {
                                                continue;
                                            } elseif ($file->getBrand() == 'NIFTY' && !$customer->getNifty()) {
                                                continue;
                                            } elseif ($file->getBrand() == 'DFS ALUM' && !$customer->getDfmal()) {
                                                continue;
                                            }
                                        } elseif ($customer->getUpdateType() == 'full' && ($file->getType() == 'aces-full' || $file->getType() == 'pies-full-xml' || $file->getType() == 'pies-full-csv' || $file->getType() == 'master' || $file->getType() == 'assetpackage')) {
                                            if ($file->getType() == 'aces-full' && $customer->getAcesVersion() == 'FLAT') {
                                                continue;
                                            } elseif ($file->getType() == 'master' && $customer->getAcesVersion() != 'FLAT') {
                                                continue;
                                            } elseif ($file->getType() == 'pies-full-xml' && $customer->getPiesVersion() == 'FLAT') {
                                                continue;
                                            } elseif ($file->getType() == 'pies-full-csv' && $customer->getPiesVersion() != 'FLAT') {
                                                continue;
                                            }

                                            if ($file->getBrand() == 'AVS' && !$customer->getAvs()) {
                                                continue;
                                            } elseif ($file->getBrand() == 'LUNDONLY' && !$customer->getLund()) {
                                                continue;
                                            } elseif ($file->getbrand() == 'LUND' && !$customer->getLundAll()) {
                                                continue;
                                            } elseif ($file->getBrand() == 'NIFTY' && !$customer->getNifty()) {
                                                continue;
                                            } elseif ($file->getBrand() == 'DFS ALUM' && !$customer->getDfmal()) {
                                                continue;
                                            }
                                        } else {
                                            continue;
                                        }
                                ?>
                        <tr>
                            <td data-title="Type">
                                        <?php
                                        switch ($file->getType()) {
                                            case 'master':
                                                echo 'Master File';
                                                break;
                                            case 'supplement':
                                                echo 'Supplement File';
                                                break;
                                            case 'aces-full':
                                                echo 'ACES Full';
                                                break;
                                            case 'aces-incr':
                                                echo 'ACES Incremental';
                                                break;
                                            case 'pies-full-xml':
                                                echo 'PIES XML Full';
                                                break;
                                            case 'pies-full-csv':
                                                echo 'PIES CSV Full';
                                                break;
                                            case 'pies-incr-xml':
                                                echo 'PIES XML Incremental';
                                                break;
                                            case 'pies-incr-csv':
                                                echo 'PIES CSV Incremental';
                                                break;
                                            case 'assetpackage':
                                                echo 'Media Asset Package';
                                                break;
                                        }
                                        ?>
                            </td>
                            <td data-title="Brand">
                                <?php 
                                if ($file->getBrand() == 'LUNDONLY') { 
                                    echo 'LUND';
                                } else if ($file->getBrand() == 'LUND') {
                                    echo 'LUND+';
                                } else {
                                    echo ($file->getBrand() ? $file->getBrand() : 'ALL');
                                }
                                ?>
                            </td>
                            <td data-title="Format"><?php echo strtoupper($file->getAsset()->getExtension()); ?></td>
                            <td data-title="Download"><a href="/assets/<?php echo $file->getAsset()->getFilePath(); ?>" target="_blank"><img src="/assets/application/lundinternational/images/download.png" /></a></td>
                        </tr>
                                <?php
                                    }
                                }
                                ?>
                    </table>
                    <?php
                            }
                        }
                    }
                    ?>
                    <table class="portal-table">
                        <thead>
                            <tr>
                                <td colspan="4">Base Snapshot</td>
                            </tr>
                        </thead>
                        <tr>
                            <th>Type</th>
                            <th>Brand</th>
                            <th>Format</th>
                            <th>Download</th>
                        </tr>
                        <?php $file = $this->fileLogService->getFileLog(null, 'master'); ?>
                        <tr>
                            <td data-title="Type">Master</td>
                            <td data-title="Brand">ALL</td>
                            <td data-title="Format">CSV</td>
                            <td data-title="Download"><a href="/assets/<?php echo $file->getAsset()->getFilePath(); ?>" target="_blank"><img src="/assets/application/lundinternational/images/download.png" /></a></td>
                        </tr>
                        <?php if ($customer->getAcesVersion() != 'FLAT') { ?>
                            <?php if ($customer->getAvs()) { ?>
                                <?php $file = $this->fileLogService->getFileLog('AVS', 'aces-full'); ?> 
                        <tr>
                            <td data-title="Type">ACES 3.0.1</td>
                            <td data-title="Brand">AVS</td>
                            <td data-title="Format">XML</td>
                            <td data-title="Download"><a href="/assets/<?php echo $file->getAsset()->getFilePath(); ?>" target="_blank"><img src="/assets/application/lundinternational/images/download.png" /></a></td>
                        </tr>
                            <?php } ?>
                            <?php if ($customer->getLundAll()) { ?>
                                <?php $file = $this->fileLogService->getFileLog('LUND', 'aces-full'); ?>
                        <tr>
                            <td data-title="Type">ACES 3.0.1</td>
                            <td data-title="Brand">LUND+</td>
                            <td data-title="Format">XML</td>
                            <td data-title="Download"><a href="/assets/<?php echo $file->getAsset()->getFilePath(); ?>" target="_blank"><img src="/assets/application/lundinternational/images/download.png" /></a></td>
                        </tr>
                            <?php } else { ?>
                                <?php if ($customer->getLund()) { ?>
                                    <?php $file = $this->fileLogService->getFileLog('LUNDONLY', 'aces-full'); ?>
                        <tr>
                            <td data-title="Type">ACES 3.0.1</td>
                            <td data-title="Brand">LUND</td>
                            <td data-title="Format">XML</td>
                            <td data-title="Download"><a href="/assets/<?php echo $file->getAsset()->getFilePath(); ?>" target="_blank"><img src="/assets/application/lundinternational/images/download.png" /></a></td>
                        </tr>
                                <?php } ?>
                                <?php if ($customer->getNifty()) { ?>
                                    <?php $file = $this->fileLogService->getFileLog('NIFTY', 'aces-full'); ?>
                        <tr>
                            <td data-title="Type">ACES 3.0.1</td>
                            <td data-title="Brand">NIFTY</td>
                            <td data-title="Format">XML</td>
                            <td data-title="Download"><a href="/assets/<?php echo $file->getAsset()->getFilePath(); ?>" target="_blank"><img src="/assets/application/lundinternational/images/download.png" /></a></td>
                        </tr>
                                <?php } ?>
                                <?php if ($customer->getDfmal()) { ?>
                                    <?php $file = $this->fileLogService->getFileLog('DFS ALUM', 'aces-full'); ?>
                        <tr>
                            <td data-title="Type">ACES 3.0.1</td>
                            <td data-title="Brand">DFS ALUM</td>
                            <td data-title="Format">XML</td>
                            <td data-title="Download"><a href="/assets/<?php echo $file->getAsset()->getFilePath(); ?>" target="_blank"><img src="/assets/application/lundinternational/images/download.png" /></a></td>
                        </tr>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>
                        <?php $pies = ($customer->getPiesVersion() == 'FLAT' ? 'pies-full-csv' : 'pies-full-xml'); ?>
                        <?php if ($customer->getAvs()) { ?>
                            <?php $file = $this->fileLogService->getFileLog('AVS', $pies); ?>
                        <tr>
                            <td data-title="Type">PIES 6.5</td>
                            <td data-title="Brand">AVS</td>
                            <td data-title="Format">XML</td>
                            <td data-title="Download"><a href="/assets/<?php echo $file->getAsset()->getFilePath(); ?>" target="_blank"><img src="/assets/application/lundinternational/images/download.png" /></a></td>
                        </tr>
                        <?php } ?>
                        <?php if ($customer->getLundAll()) { ?>
                            <?php $file = $this->fileLogService->getFileLog('LUND', $pies); ?>
                        <tr>
                            <td data-title="Type">PIES 6.5</td>
                            <td data-title="Brand">LUND+</td>
                            <td data-title="Format">XML</td>
                            <td data-title="Download"><a href="/assets/<?php echo $file->getAsset()->getFilePath(); ?>" target="_blank"><img src="/assets/application/lundinternational/images/download.png" /></a></td>
                        </tr>
                        <?php } else { ?>
                            <?php if ($customer->getLund()) { ?>
                                <?php $file = $this->fileLogService->getFileLog('LUNDONLY', $pies); ?>
                        <tr>
                            <td data-title="Type">PIES 6.5</td>
                            <td data-title="Brand">LUND</td>
                            <td data-title="Format">XML</td>
                            <td data-title="Download"><a href="/assets/<?php echo $file->getAsset()->getFilePath(); ?>" target="_blank"><img src="/assets/application/lundinternational/images/download.png" /></a></td>
                        </tr>
                            <?php } ?>
                            <?php if ($customer->getNifty()) { ?>
                                <?php $file = $this->fileLogService->getFileLog('NIFTY', $pies); ?>
                        <tr>
                            <td data-title="Type">PIES 6.5</td>
                            <td data-title="Brand">NIFTY</td>
                            <td data-title="Format">XML</td>
                            <td data-title="Download"><a href="/assets/<?php echo $file->getAsset()->getFilePath(); ?>" target="_blank"><img src="/assets/application/lundinternational/images/download.png" /></a></td>
                        </tr>
                            <?php } ?>
                            <?php if ($customer->getDfmal()) { ?>
                                <?php $file = $this->fileLogService->getFileLog('DFS ALUM', $pies); ?>
                        <tr>
                            <td data-title="Type">PIES 6.5</td>
                            <td data-title="Brand">DFS ALUM</td>
                            <td data-title="Format">XML</td>
                            <td data-title="Download"><a href="/assets/<?php echo $file->getAsset()->getFilePath(); ?>" target="_blank"><img src="/assets/application/lundinternational/images/download.png" /></a></td>
                        </tr>
                            <?php } ?>
                        <?php } ?>
                        <?php if ($customer->getAvs()) { ?>
                            <?php $file = $this->fileLogService->getFileLog('AVS', 'assetpackage'); ?>
                        <tr>
                            <td data-title="Type">Media Assets</td>
                            <td data-title="Brand">AVS</td>
                            <td data-title="Format">ZIP</td>
                            <td data-title="Download"><a href="/assets/<?php echo $file->getAsset()->getFilePath(); ?>" target="_blank"><img src="/assets/application/lundinternational/images/download.png" /></a></td>
                        </tr>
                        <?php } ?>
                        <?php if ($customer->getLundAll()) { ?>
                            <?php $file = $this->fileLogService->getFileLog('LUND', 'assetpackage'); ?>
                        <tr>
                            <td data-title="Type">Media Assets</td>
                            <td data-title="Brand">LUND+</td>
                            <td data-title="Format">ZIP</td>
                            <td data-title="Download"><a href="/assets/<?php echo $file->getAsset()->getFilePath(); ?>" target="_blank"><img src="/assets/application/lundinternational/images/download.png" /></a></td>
                        </tr>
                        <?php } else { ?>
                            <?php if ($customer->getLund()) { ?>
                                <?php $file = $this->fileLogService->getFileLog('LUNDONLY', 'assetpackage'); ?>
                        <tr>
                            <td data-title="Type">Media Assets</td>
                            <td data-title="Brand">LUND</td>
                            <td data-title="Format">ZIP</td>
                            <td data-title="Download"><a href="/assets/<?php echo $file->getAsset()->getFilePath(); ?>" target="_blank"><img src="/assets/application/lundinternational/images/download.png" /></a></td>
                        </tr>
                            <?php } ?>
                            <?php if ($customer->getNifty()) { ?>
                                <?php $file = $this->fileLogService->getFileLog('NIFTY', 'assetpackage'); ?>
                        <tr>
                            <td data-title="Type">Media Assets</td>
                            <td data-title="Brand">NIFTY</td>
                            <td data-title="Format">ZIP</td>
                            <td data-title="Download"><a href="/assets/<?php echo $file->getAsset()->getFilePath(); ?>" target="_blank"><img src="/assets/application/lundinternational/images/download.png" /></a></td>
                        </tr>
                            <?php } ?>
                            <?php if ($customer->getDfmal()) { ?>
                                <?php $file = $this->fileLogService->getFileLog('DFS ALUM', 'assetpackage'); ?>
                        <tr>
                            <td data-title="Type">Media Assets</td>
                            <td data-title="Brand">DFS ALUM</td>
                            <td data-title="Format">ZIP</td>
                            <td data-title="Download"><a href="/assets/<?php echo $file->getAsset()->getFilePath(); ?>" target="_blank"><img src="/assets/application/lundinternational/images/download.png" /></a></td>
                        </tr>
                            <?php } ?>
                        <?php } ?>
                    </table>
                    <div id="file-manager"></div>
                </div>
