<?php
$form = $this->form;
$form->setAttributes(array(
    'action' => '/about-us/dealers-edge',
    'method' => 'POST',
    'id'     => 'forms',
))->prepare();
$fieldset = $form->getBaseFieldset();
$errors = $this->formElementErrors()
            ->setMessageOpenFormat('<span class="help-block">')
            ->setMessageSeparatorString('</span><span class="help-block">')
            ->setMessageCloseString('</span>');
?>
                <div class="col1">
                    <img class="image-header" src="/assets/application/lundinternational/images/dealers-edge-banner.jpg" style="margin-bottom:-40px;" />
                </div>
                <div class="coll">
                    <article>
                        <p>Designing top-quality, great-looking accessories your customers want is our focus at AVS and LUND. We also put a premium on retailer service as well as marketing and distribution programs to make your sales efforts even more successful. Join now, and you'll have access to free point-of-purchase displays when you buy minimum quantities of our products - and much, much more!</p>
                        <h2 class="title">Dealers Edge Benefits:</h2>
                        <div class="dealers_edge">
                            <ul>
                                <li>Monthly and quarterly communications keep you up to date</li>
                                <li>Application Guides</li>
                                <li>Store locations featured in our Retail Locator</li>
                                <li>Exposure to millions of annual website visitors</li>
                                <li>Access to FREE POP displays</li>
                                <li>Monthly promotions (free prize drawings)</li>
                                <li>Marketing support</li>
                                <li>Product installation videos</li>
                            </ul>
                        </div>
                        <p>When you consider all there is to offer, joining Dealers Edge is clearly a smart move.</p>
                        <h2 class="title">Retail Store Listings</h2>
                        <a href="/where-to-buy"><img class="dropshadow" alt="Where To Buy" src="/assets/application/lundinternational/images/location_callout.jpg"></a>
                        <p>As a member, your store locations will be included in our online Retail Locator.</p>
                        <h2 class="title">Access to Videos</h2>
                        <a href="/customer-care/installation"><img class="dropshadow" alt="Installation Videos" src="/assets/application/lundinternational/images/install_callout.jpg"></a>
                        <p>We provide you access to videos demonstrating how easy our products are to install along with their features and benefits.</p>
                    </article>
                </div>
                <div class="colr">
                    <div class="module-b">
                        <?php if ($this->result == 'success') { ?>
                        <p>Thank you for your interest in Lund International’s Dealers Edge Program. An e-mail has been sent to you with more details. If you do not receive an e-mail within 1 hour, please e-mail <a href=mailto:dealersedgeadmin@lundinter.com>dealersedgeadmin@lundinter.com</a></p>
                        <p>The Lund International Marketing Team</p>
                        <?php } else { ?>
                            <?php if ($this->result == 'error') { ?>
                            <p style="color:#ff0000"><strong>There was an error processing your request.</strong></p>
                            <?php } ?>
                        <p>Complete the form below to become an authorized dealer and Dealers Edge member, and you'll be on your way to increasing your sales and reaping the rewards!</p>
                        <?php echo $this->form()->openTag($form); ?>
                        <?php echo $this->formElement($form->get('secret')); ?>
                        <input type="hidden" name="dealers-edge-fieldset[disabled]" value="0" />
                        <input type="hidden" name="dealers-edge-fieldset[site]" value="<?php echo $this->site->getSiteId(); ?>" />
                        <div class="form-row">
                            <?php $existingDealer = $fieldset->get('existingDealer'); ?>
                            <?php echo $this->formElement($existingDealer); ?>
                        </div>
                        <div class="formcolumn">
                            <?php $firstName = $fieldset->get('firstName'); ?>
                            <label><?php echo $firstName->getLabel() ?> *</label><?php echo $this->formElement($firstName); ?>
                            <?php $lastName = $fieldset->get('lastName'); ?>
                            <label><?php echo $lastName->getLabel() ?> *</label><?php echo $this->formElement($lastName); ?>
                            <?php $emailAddress = $fieldset->get('emailAddress'); ?>
                            <label><?php echo $emailAddress->getLabel() ?> *</label><?php echo $this->formElement($emailAddress); ?>
                            <?php $phoneNumber = $fieldset->get('phoneNumber'); ?>
                            <label><?php echo $phoneNumber->getLabel() ?> *</label><?php echo $this->formElement($phoneNumber); ?>
                            <?php $faxNumber = $fieldset->get('faxNumber'); ?>
                            <label><?php echo $faxNumber->getLabel() ?> </label><?php echo $this->formElement($faxNumber); ?>
                            <?php $companyName = $fieldset->get('companyName'); ?>
                            <label><?php echo $companyName->getLabel() ?> *</label><?php echo $this->formElement($companyName); ?>
                        </div>
                        <div class="formcolumn">
                            <?php $streetAddress = $fieldset->get('streetAddress'); ?>
                            <label><?php echo $streetAddress->getLabel() ?> *</label><?php echo $this->formElement($streetAddress); ?>
                            <?php $locality = $fieldset->get('locality'); ?>
                            <label><?php echo $locality->getLabel() ?> *</label><?php echo $this->formElement($locality); ?>
                            <?php $region = $fieldset->get('region'); ?>
                            <label><?php echo $region->getLabel() ?> *</label><?php echo $this->formElement($region); ?>
                            <?php $postCode = $fieldset->get('postCode'); ?>
                            <label><?php echo $postCode->getLabel() ?> *</label><?php echo $this->formElement($postCode); ?>
                            <?php $country = $fieldset->get('country'); ?>
                            <label><?php echo $country->getLabel() ?> *</label><?php echo $this->formElement($country); ?>
                            <?php $distributor = $fieldset->get('distributor'); ?>
                            <label><?php echo $distributor->getLabel() ?> </label><?php echo $this->formElement($distributor); ?>
                        </div>
                        <div class="form-row" style="padding: 15px 0;">
                            <?php $brands = $fieldset->get('brands'); ?>
                            <label id="DE-brand"><?php echo $brands->getLabel() ?></label>
                            <?php echo $this->formElement($brands); ?>
                        </div>
                        <input id="dealedgesub" class="btn btn-submit" type="submit" name="submit" value="Submit" onclick="_gaq.push(['_trackEvent','Dealers Edge','Submit'])">
                        <?php echo $this->form()->closeTag($form); ?>
                        <?php } ?>
                    </div>
                    <div class="module-b">
                        <ul class="col2">
                            <li>
                                <h2 class="title">Point of Purchase Displays</h2>
                                The Dealers Edge Program gives you the chance to select from an array of displays to merchandise products and market more effectively to your customer. You'll sell more if they can see it and touch it. Displays are available for leading AVS and LUND product categories.
                            </li>
                            <li>
                                <div class="module-a">
                                    <p class="boxes" style="width:80%;">
                                        <strong>Marketing Materials Order Form</strong><br>
                                        <a class="redLink" href="/assets/library/cms/Dealers_Edge_POP_Lit_OrderForm_NO_Aeroskin.pdf">Click to download PDF.</a>
                                    </p>
                                    <a href="/assets/library/cms/Dealers_Edge_POP_Lit_OrderForm_NO_Aeroskin.pdf"><img align="right" alt="PDF Download" src="/assets/application/lundinternational/images/icon-pdf.png"></a>
                                    <p class="boxes">You will need your username and password provided via email. Can't find? Email us at <a class="redLink" href="mailto:dealersedge@lundinter.com">dealersedge@lundinter.com</a></p>
                                </div>
                            </li>
                        </ul>
                        <ul class="list-displays">
                            <li>
                                <img src="/assets/application/lundinternational/images/explorer-bugreflector.png" />
                                <p>AVS</p>
                                <strong>Buy 6 AVS BUGFLECTOR II Products<br>Get a FREE POP Display<br><br>Buy 6 AVS AEROSKIN Products<br>Get a FREE POP Display</strong>
                                <em>Buy 13 AVS Ventvisor or Hood<br>Protection Products<br>Get a FREE POP Display<br><br>Buy 9 AEROSKIN Products<br>Get a FREE POP Display</em>
                            </li>
                            <li>
                                <img src="/assets/application/lundinternational/images/gmc-dealers-edge.png" />
                                <p>LUND</p>
                                <strong>Buy 4 LUND Catch-All Carpet Products<br>Get a FREE POP Display<br><br>Buy 4 LUND Catch-It Vinyl Products<br>Get a FREE POP Display<br><br>Buy 4 LUND Catch-It Carpet Products<br>Get a FREE POP Display</strong>
                                <em>Buy 2 LUND Running Board / Nerf Bars<br>Get a FREE POP Display<br><br>Buy 2 LUND Tonneau Covers<br>Get a FREE POP Display</em>
                            </li>
                        </ul>
                        <div class="clear"></div>
                        <p>We are committed to providing quality POP displays at nominal cost. In most cases, you can get them FREE with a minimum purchase qualifying you as an official Dealers Edge Member.</p>
                    </div>
                    <p class="note">The Dealers Edge Rewards Program is being offered solely for the convenience of Lund International and its affiliates and may be discontinued at any time. All aspects of the program are subject to modification, cancellation, or limitation at the sole discretion of Lund at any time and from time to time, with or without notice.</p>
                    <div class="module-g-de">
                        <span><strong>MAP Policy</strong><br>
                        To protect the investment of our high-quality dealers and Lund International's brand reputation, we have unilaterally adopted a MINIMUM ADVERTISED PRICE POLICY ("MAP Policy").</span><br />
                        <span class="month_info">For the month of May 2014, Lund International's MAP Policy will be suspended for the following products: LUND Ventvisor Elite, LUND Interceptor, LUND Elite Fender Flares and LUND Genesis Elite Tonneaus.</span>
                        <ul>
                            <li>
                                <strong>MAP Policy</strong><br>
                                <a class="redLink" href="/assets/library/cms/Lund-MAP-Policy.pdf">Click to download PDF.</a>
                                <a href="/assets/library/cms/Lund-MAP-Policy.pdf"><img align="right" alt="PDF Download" src="/assets/application/lundinternational/images/icon-pdf.png" style="margin-top:-20px;"></a>
                            </li>
                            <li>
                                <strong>MAP Policy FAQs</strong><br>
                                <a class="redLink" href="/assets/library/cms/lund_MAP-FAQs.pdf">Click to download PDF.</a>
                                <a href="/assets/library/cms/lund_MAP-FAQs.pdf"><img align="right" alt="PDF Download" src="/assets/application/lundinternational/images/icon-pdf.png" style="margin-top:-20px;"></a>
                            </li>
                            <li>You will need your username and password provided via email. Can't find? Email us at <a class="redLink" href="mailto:dealersedge@lundinter.com">dealersedge@lundinter.com</a></li>
                        </ul>
                    </div>
                    <div class="clear"></div>
                </div>
