                    <div class="colr">
                        <h2 class="title">Installation Guides</h2>
                        <?php if ($this->partRecord) { ?>
                        <hr />
                        <h2><?php echo $this->partRecord->getProductLine()->getDisplayName(); ?> Installation</h2>
                            <?php if ($this->partRecord->getProductLine()->getInstallationVideo()) { ?>
                        <p>This installation video will help you get started!</p>
                        <a class="youtube cboxElement" href="http://www.youtube.com/embed/<?php echo $this->partRecord->getProductLine()->getInstallationVideo(); ?>">
                            <img src="http://img.youtube.com/vi/<?php echo $this->partRecord->getProductLine()->getInstallationVideo(); ?>/0.jpg" width="294" height="200" />
                        </a>
                        <hr />
                            <?php } ?>
                            <?php if ($this->partRecord->getIsheet()) { ?>
                        <p>For proper installation and best possible fit, please read all instructions BEFORE you begin. Download the PDF to get started.</p>
                        <p><a href="/assets/library/products/isheets/<?php echo $this->partRecord->getIsheet(); ?>.pdf" class="btn btn-download" target="_blank" style="float:left; clear:left;"><span>Download Installation Guide</span></a><img src="/assets/application/lundinternational/images/pdficon_large.png" border="0" /></p>
                            <?php } else { ?>
                        <p>We're sorry, no installation guide was found.</p>
                            <?php } ?>
                        <p>For technical assistance or to obtain missing parts, please call<br>
                        Customer Relations at <strong>1-800-241-7219</strong>.</p>
                        <p>Not the product you were looking for? <a href="/customer-care/installation" style="color:#cc3333;">Try another search.</a></p>
                        <?php } else if ($this->plRecords) { ?>
                            <?php if ($this->multiple) { ?>
                        <hr />
                        <p>More than one product matched your search. Please choose your product below:</p>
                        <ul>
                                <?php foreach($this->plRecords as $record) { ?>
                            <li><a href="#" id="install<?php echo $record['productLine']->getProductLineId(); ?>" class="installexpand" style="color:#cc3333;"><?php echo $record['productLine']->getDisplayName(); ?></a>
                                <div id="install<?php echo $record['productLine']->getProductLineId(); ?>exp" class="installexp" style="display:none;">
                                    <?php if ($record['productLine']->getInstallationVideo()) { ?>
                                    <div class="install-video">
                                        <p>This installation video will help you get started!</p>
                                        <a class="youtube cboxElement" href="http://www.youtube.com/embed/<?php echo $record['productLine']->getInstallationVideo(); ?>">
                                            <img src="http://img.youtube.com/vi/<?php echo $record['productLine']->getInstallationVideo(); ?>/0.jpg" width="294" height="200" />
                                        </a>
                                    </div>
                                    <?php } ?>
                                    <?php foreach($record['parts'] as $part) { ?>
                                        <?php if ($part->getIsheet()) { ?>
                                    <p class="install-pdf">PDF Installation Guide: <a class="btn btn-download" href="/assets/library/products/isheets/<?php echo $part->getIsheet(); ?>.pdf" target="_blank"><span>Download Installation Guide</span></a></p>
                                    <div class="clear"></div>
                                            <?php break; ?>
                                        <?php } ?>
                                    <?php } ?>
                                </div>
                            </li>
                                <?php } ?>
                        </ul>
                        <script language="javascript">
                        $(document).ready(function() {
                        $(function() {
                            $('.installexpand').click(function() {
                                $('#'+$(this).attr('id')+'exp').toggle();
                                return false;
                            });
                            $('.installexp').hide();
                        });
                        });
                        </script>
                            <?php } else { ?>
                                <?php $productLine = $this->plRecords[0]['productLine']; ?>
                                <?php $parts = $this->plRecords[0]['parts']; ?>
                        <hr />  
                        <h2><?php echo $productLine->getDisplayName(); ?> Installation</h2>  
                                <?php if ($productLine->getInstallationVideo()) { ?>
                        <p>This installation video will help you get started!</p>
                        <a class="youtube cboxElement" href="http://www.youtube.com/embed/<?php echo $productLine->getInstallationVideo(); ?>">
                            <img src="http://img.youtube.com/vi/<?php echo $this->partRecord->getProductLine()->getInstallationVideo(); ?>/0.jpg" width="294" height="200" />
                        </a>
                        <hr />
                                <?php } ?>
                                <?php foreach($parts as $part) { ?>
                                    <?php if ($part->getIsheet()) { ?>
                        <p>For proper installation and best possible fit, please read all instructions BEFORE you begin. Download the PDF to get started.</p>
                        <p><a href="/assets/library/products/isheets/<?php echo $part->getIsheet(); ?>.pdf" class="btn btn-download" target="_blank" style="float:left; clear:left;"><span>Download Installation Guide</span></a><img src="/assets/application/lundinternational/images/pdficon_large.png" border="0" /></p>
                                        <?php break; ?>
                                    <?php } ?>
                                <?php } ?>
                            <?php } ?>
                        <p>For technical assistance or to obtain missing parts, please call<br>
                        Customer Relations at <strong>1-800-241-7219</strong>.</p>
                        <p>Not the product you were looking for? <a href="/customer-care/installation" style="color:#cc3333;">Try another search.</a></p>
                        <?php } else { ?>
                        <p>Enter a product name or part # below to search for installation guides.</p>
                        <form class="search" name="Search_Installation_Guides" id="installation-search" method="POST" action="/customer-care/installation">
                        <input type="text" name="searchquery" placeholder="Search by Part Name or Part #" /><br><br>
                        <input type="submit" name="search" value="Search" />
                        </form>
                        <div class="clear"></div>
                        <h2 class="title">Installation Videos</h2>
<p>Take a look at the handy videos below developed to walk you through the installation process.<br />View more of our installation videos on our <a href="http://www.youtube.com/user/LundInternational" class="red" target="_blank">YouTube Channel &raquo;</a></p>
<h2 class="title">AVS</h2>
<ul class="list-vehicles">
<li>
<a href="http://www.youtube.com/embed/ilNRXLyuUog" class="youtube"><img src="http://img.youtube.com/vi/ilNRXLyuUog/0.jpg" /></a>
<ul>
<li><a href="http://www.youtube.com/embed/ilNRXLyuUog" class="youtube">Aeroskin</a></li>
<li><a href="http://www.youtube.com/embed/ilNRXLyuUog" class="youtube">View</a></li>
</ul>
</li>
<li>
<a href="http://www.youtube.com/embed/Vuk388oyoYM" class="youtube"><img src="http://img.youtube.com/vi/Vuk388oyoYM/0.jpg" /></a>
<ul>
<li><a href="http://www.youtube.com/embed/Vuk388oyoYM" class="youtube">Bugflector II</a></li>
<li><a href="http://www.youtube.com/embed/Vuk388oyoYM" class="youtube">View</a></li>
</ul>
</li>
<li>
<a href="http://www.youtube.com/embed/JEgdLUVviTM" class="youtube"><img src="http://img.youtube.com/vi/JEgdLUVviTM/0.jpg" /></a>
<ul>
<li><a href="http://www.youtube.com/embed/JEgdLUVviTM" class="youtube">Low Profile Ventvisor</a></li>
<li><a href="http://www.youtube.com/embed/JEgdLUVviTM" class="youtube">View</a></li>
</ul>
</li>
<li>
<a href="http://www.youtube.com/embed/6-4v38L-4gU" class="youtube"><img src="http://img.youtube.com/vi/6-4v38L-4gU/0.jpg" /></a>
<ul>
<li><a href="http://www.youtube.com/embed/6-4v38L-4gU" class="youtube">Carflector</a></li>
<li><a href="http://www.youtube.com/embed/6-4v38L-4gU" class="youtube">View</a></li>
</ul>
</li>
<li>
<a href="http://www.youtube.com/embed/OVQt6-JrP1g" class="youtube"><img src="http://img.youtube.com/vi/OVQt6-JrP1g/0.jpg" /></a>
<ul>
<li><a href="http://www.youtube.com/embed/OVQt6-JrP1g" class="youtube">In-Channel Ventvisor</a></li>
<li><a href="http://www.youtube.com/embed/OVQt6-JrP1g" class="youtube">View</a></li>
</ul>
</li>
<li>
<a href="http://www.youtube.com/embed/gQGTAQodJCg" class="youtube"><img src="http://img.youtube.com/vi/gQGTAQodJCg/0.jpg" /></a>
<ul>
<li><a href="http://www.youtube.com/embed/gQGTAQodJCg" class="youtube">The Original Ventvisor</a></li>
<li><a href="http://www.youtube.com/embed/gQGTAQodJCg" class="youtube">View</a></li>
</ul>
</li>
</ul>
<div class="clear"></div>
<h2 class="title">LUND</h2>
<ul class="list-vehicles">
<li>
<a href="http://www.youtube.com/embed/PYB1k5ABjM8" class="youtube"><img src="http://img.youtube.com/vi/PYB1k5ABjM8/0.jpg" /></a>
<ul>
<li><a href="http://www.youtube.com/embed/PYB1k5ABjM8" class="youtube">Interceptor Hood Shield</a></li>
<li><a href="http://www.youtube.com/embed/PYB1k5ABjM8" class="youtube">View</a></li>
</ul>
</li>
<li>
<a href="http://www.youtube.com/embed/SJrVbPbZLBQ" class="youtube"><img src="http://img.youtube.com/vi/SJrVbPbZLBQ/0.jpg" /></a>
<ul>
<li><a href="http://www.youtube.com/embed/SJrVbPbZLBQ" class="youtube">Genesis Roll-Up Tonneau</a></li>
<li><a href="http://www.youtube.com/embed/SJrVbPbZLBQ" class="youtube">View</a></li>
</ul>
</li>
<li>
<a href="http://www.youtube.com/embed/WmGHt3pikcc" class="youtube"><img src="http://img.youtube.com/vi/WmGHt3pikcc/0.jpg" /></a>
<ul>
<li><a href="http://www.youtube.com/embed/WmGHt3pikcc" class="youtube">Genesis Elite</a></li>
<li><a href="http://www.youtube.com/embed/WmGHt3pikcc" class="youtube">View</a></li>
</ul>
</li>
<div class="clear"></div>
<li>
<a href="http://www.youtube.com/embed/2iwJz5xLsI8" class="youtube"><img src="http://img.youtube.com/vi/2iwJz5xLsI8/0.jpg" /></a>
<ul>
<li><a href="http://www.youtube.com/embed/2iwJz5xLsI8" class="youtube">Trail Runner Board</a></li>
<li><a href="http://www.youtube.com/embed/2iwJz5xLsI8" class="youtube">View</a></li>
</ul>
</li>
</ul>
<div class="clear"></div>
<?php } ?>
                    </div>
