                    <div class="colr">
                        <h1 class="title">Online Retailers</h1>
                        <p>Congratulations! You're ever so close to finding the AVS or LUND product that's right for your truck, SUV, CUV, van or passenger car. Our AVS and LUND products are sold through over 25 online retailers and can be delivered direct to your doorstep.</p>
                        <p>Click on any of the online retailers below to buy our products or to view online specials currently in market.</p>
                        <p><img src="/assets/application/lundinternational/images/retailers_discount_dark.png"> = Online Special (Located in lower right-hand corner if online promotion is in market)</p>
                        <div class="module-e">
                            <ul class="list-logos">
                                <?php foreach ($this->retailers as $retailer) { ?>
                                <li><a href="<?php echo $retailer->getWebsite(); ?>"<?php echo ($retailer->getDiscount() ? ' class="discount"' : ''); ?> target="_blank"><img src="<?php echo (null != $retailer->getLogoAsset() ? '/assets/' . $retailer->getLogoAsset()->getFilePath() : ''); ?>" border="0" alt="<?php echo $retailer->getCompanyName(); ?>" /></a>
                                    <?php if ($retailer->getDiscount()) { ?>
                                    <div style="display:none">
                                        <div class="inline_discount">
                                            <h3>Current Promotion - <?php echo $retailer->getCompanyName(); ?></h3>
                                            <?php if (null != $retailer->getDiscountAsset()) { ?>
                                            <p style="margin-top: 15px;"><a href="<?php echo $retailer->getDiscountUrl(); ?>" target="_blank"><img src="/assets/<?php echo $retailer->getDiscountAsset()->getFilePath(); ?>" /></a></p>
                                            <?php } ?>
                                            <?php if ($retailer->getDiscountCopy()) { ?>
                                            <p style="margin-top: 15px;"><?php echo $retailer->getDiscountCopy(); ?></p>
                                            <?php } ?>
                                    <?php } ?>
                                </li>
                                <?php } ?>
                            </ul>
                            <script>
                            $(document).ready(function() {
                                $('.module-e .list-logos a.discount').each(function(){
                                    $(this).after('<div class="discount_img"><img src="/assets/application/lundinternational/images/retailers_discount.png" alt="Discounted Retailer"/></div>');
                                    $('.discount_img').hover(function(){
                                        $(this).find('img').attr('src','/assets/application/lundinternational/images/retailers_discount_dark.png');
                                    },function(){
                                        $(this).find('img').attr('src','/assets/application/lundinternational/images/retailers_discount.png');
                                    });
                                });
                                $('.discount_img').on('click', function(e){
                                    e.preventDefault();
                                    var popContent = $(this).next().find('.inline_discount');
                                    $.colorbox({inline:true, href:popContent, width:'auto'});
                                });
                            });
                            </script>
                        </div>
                    </div>
