<?php
$form = $this->form;
$form->setAttributes(array(
    'action' => '/showroom',
    'method' => 'POST',
    'id'     => 'forms',
))->prepare();
$fieldset = $form->getBaseFieldset();
$errors = $this->formElementErrors()
            ->setMessageOpenFormat('<span class="help-block">')
            ->setMessageSeparatorString('</span><span class="help-block">')
            ->setMessageCloseString('</span>');
?>
                <script src="/assets/application/lundinternational/js/jquery.cycle.all.js" type="text/javascript"></script>
                <script src="/assets/application/lundinternational/js/modernizr.custom.js" type="text/javascript"></script>
                <script src="/assets/application/lundinternational/js/jquery.colorbox.js" type="text/javascript"></script>
                <link href="/assets/application/lundinternational/css/showroom.css" media="screen" rel="stylesheet" type="text/css" />
                <script type="text/javascript">
					$(document).ready(function(){
					    $(".group1").colorbox({rel:'group1'});
			            $('#rotator').before('<ul id="pager_nav">').cycle({ 
                            fx:      'fade', 
                            /*speed:    600, 
                            timeout:  5000, */
                            pause: true,
                            next:   '#slider_right', 
                            prev:   '#slider_left',
                            pager:  '#pager_nav',
                            pagerAnchorBuilder: function(idx, slide) {
                                return '<li><a href="#"><div class="circle"></div><img src="' + jQuery(slide).find('img').attr('src') + '" width="150" height="60" /></a></li>'; 
                            } 
                        });
                        $('#pager_nav .circle').hover(function(){
                            $(this).next('img').fadeIn('fast');
                        },function(){
                            $(this).next('img').fadeOut('fast');
                        });
					});
				</script>
                    <script type="text/javascript" src="/assets/application/lundinternational/js/jquery.pages.js"></script>
                    <script type="text/javascript">
                        $(document).ready(function() {
                            $("div.holder").jPages({
                                containerID : "paginatedcontent",
                                perPage: 12
                            });
                        });
                    </script>
                    <div id="content_wrapper">
                        <img src="/assets/application/lundinternational/images/slder-arrowL.png" alt="move slider left" id="slider_left"/>
                        <div id="rotator">
                            <div>
                                 <div class="caption">LUND Interceptor, Ventvisor Elite, <br />Summit Ridge Running Boards, <br />SX-Sport Style Fender Flares</div>
                                <img class="alignnone size-full wp-image-121" title="rain" src="/assets/application/lundinternational/images/showroomSILVERADOShowroomSlider.jpg" alt="" />
                            </div>
                            <div>
                                <div class="caption" id="construction">Chrome AVS Aeroskin, Low Profile Ventvisor, LUND 3inch<br />Stainless Steel Nerf Bars, SX-Sport Style Fender Flares</div>
                                <img class="alignnone size-full wp-image-120" title="rain3" src="/assets/application/lundinternational/images/showroom/DODGEShowroomSlider.jpg" alt="" />
                            </div>
                            <div>
                                  <div class="caption" id="mothers2">AVS Bugflector II, In-Channel Ventvisor,<br />LUND Summit Ridge Running Boards, <br />EX-ExtraWide Style Fender Flares</div>
                                  <img class="alignnone size-full wp-image-122" title="rain" src="/assets/application/lundinternational/images/showroom/FORDShowroomSlider.jpg" alt="" />
                              </div>
                              <div>
                                  <div class="caption">AVS Low Profile Ventvisor, LUND 5" Black Oval Bent Nerf Bars, <br />Genesis Tri-Fold Tonneau Cover</div>
                                  <img class="alignnone size-full wp-image-118" title="rain" src="/assets/application/lundinternational/images/showroom/camping.jpg" alt="" />
                              </div>
                              <div>
                                  <div class="caption">AVS Aeroskin, The Original Ventvisor</div>
                                  <img class="alignnone size-full wp-image-119" title="rain2" src="/assets/application/lundinternational/images/showroom/carwash.jpg" alt="" />
                              </div>
                              <div>
                                  <div class="caption" id="construction">AVS Aeroskin, Low Profile Ventvisor</div>
                                  <img class="alignnone size-full wp-image-120" title="rain3" src="/assets/application/lundinternational/images/showroom/construction.jpg" alt=""  />
                              </div>
                              <div>
                                  <div class="caption" id="mothers">AVS The Original Ventvisor and Aeroskin<br />LUND Crossroads Running Boards</div>
                                  <img class="alignnone size-full wp-image-120" title="rain3" src="/assets/application/lundinternational/images/showroom/mothers.jpg" alt=""/>
                              </div>
                              <div>
                                  <div class="caption" id="mothers2">AVS In-Channel Ventvisor, LUND <br />Aluminum Cross Bed Storage Box,<br />Latitude Nerf Bars</div>
                                  <img class="alignnone size-full wp-image-120" title="rain3" src="/assets/application/lundinternational/images/showroom/StorageBoxShowroomSlider.jpg" alt="" />
                              </div>
                              <div>
                                  <div class="caption">AVS Low Profile Ventvisor, AMP Research<br />PowerStep, BedStep, BedXtender HD<br />Moto, BedStep2</div>
                                  <img class="alignnone size-full wp-image-120" title="rain3" src="/assets/application/lundinternational/images/showroom/AMPShowroomSlider.jpg" alt="" />
                              </div>
                          </div>
                          <img src="/assets/application/lundinternational/images/slder-arrowR.png" alt="move slider right" id="slider_right"/>
                    
                    	<h1>Welcome to Our Showroom!</h1>
                    	<p>Browse our AVS and LUND showroom to see the various styles and functionality of our products in real-life scenarios along for the ride on trucks, SUVs, CUVs, vans and passenger cars. Our extensive line of automotive accessories includes everything from ventvisors/side window deflectors and hood protection to running boards / nerf bars and tonneau covers and so much more.</p>
                        </div>
                        	<div id="showroom_form">
                        		<h1>Show &amp; Tell</h1>
                        		<p>Most of us have a strong relationship with our ride – love or hate. In fact, we usually have part of our personal identity tied up in the vehicle we drive. You’re invited to share your story – better yet send us photos and a caption that best summarizes your relationship with your ride. And, if you have any AVS or LUND products installed on your ride – we’ll make sure your “show &amp; tell” is highlighted in our Showroom Gallery.</p>
                                <?php if ($this->result == 'succes') { ?>
                                <strong>Thank you for sending us your story. We will review your submission.</strong>
                                <?php } else { ?>
                        		<form name="Upload_Showroom" id="uploadimage_form" method="POST" enctype="multipart/form-data" accept-charset="utf-8" ><strong>Complete the form below and feel free to upload a picture along with your story.</strong><br><br>
                                <ul>
                                	<li>
                                 		<label>First Name</label>
                                        <input id="userinfo" type="text" name="firstname" value="" >
                                    </li>
                                    <li>
                                    	<label>Last Name</label>
                                        <input id="userinfo" type="text" name="lastname" value="" >
                                    </li>
                                    <li>
		                                 <label style="width: 100px;">Email</label><br>
                                         <input id="userinfo" type="text" name="email" value="" >
                                    </li>
                                </ul>
                                 
                                 
                                  
                        			<div id="vehicle_type">
                                    <p>Vehicle Type(s) Owned: (please check all that apply)</p>
                                    	<ul>
                                        	<li>
                                            	<input type="checkbox" name="truck" value="yes"><label>Truck</label>
                                            </li>
                                            <li>
                                            	<input type="checkbox" name="suv" value="yes"><label>SUV</label>
                                           	</li>
                                           	<li>
                                       			<input type="checkbox" name="cuv" value="yes"  ><label>CUV</label>
                                        
                                        	</li>
                                            <li>
                                            	<input type="checkbox" name="van" value="yes"  ><label>Van</label>
                                            </li>
                                            <li>
                                                <input type="checkbox" name="passengercar" value="yes"  ><label>Passenger Car</label>
                                            </li>
                                        </ul>
                     				</div>
                       			<p>Do you have a love or hate relationship with your vehicle? Share your story and you may win FREE products!</p>
                       			<span>(not to exceed 50 words)</span>
                       			<textarea rows="2" cols="50" name="story"></textarea>
                        			<div id="permissions">
                            			<input type="checkbox" value="yes" id="permbox"  name="permission"  >
                            			<label>I GIVE LUND INTERNATIONAL MY PERMISSION TO QUOTE FROM MY COMMENTS, AND USE THESE QUOTATIONS IN ADS, WEB COPY, BROCHURES, MAIL AND OTHER PROMOTIONS.</label>
                        			</div>
                       				<div id="uploadimage">
                           					<div class="uploader">
                               					<input type="file" name="imagefiles" id="imagefiles"/>
                            				</div>
                           				<div class="image_details_textfield"></div>
                           				<div class="submit"><br />
                               			<input class="button-primary" type="submit" name="uploadimage" id="uploadimage_btn" value="Upload" >
                          				</div>
                       				</div>
                        	</form>
                            <?php } ?>
                   		</div>
                    	<div id="showroom_gallery" class="colr">
                            <h3>Check out our Show &amp; Tell Gallery</h3>
                            <!--<h5 class="showroom">Let us know what images you like best by clicking below and selecting the "Favorite" button at the bottom left of each expanded image.</h5>-->
                            <div class="holder"></div>
                            <div class="module-b">
                                <ul class="list-vehicles-products" id="paginatedcontent">
                                    <?php foreach ($this->showrooms as $showroom) { ?>
                                    <li>
                                        <a class="group1" href="/assets/<?php echo $showroom->getAsset()->getFilePath(); ?>" title="<?php echo $showroom->getComments(); ?>"><img src="/admin/imagine/<?php echo $showroom->getAsset()->getHash(); ?>/122/122" alt="img<?php echo $showroom->getShowroomId(); ?>" /></a>
                                    </li>
                                    <?php } ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
