<?php
$menu = $this->layout()->menuService->getMenuByShortCode($this->layout()->site, 'main-menu');
$activeElement = $this->layout()->menuElementService->getMenuElementByUrl($menu, '/' . $this->layout()->page->getSlug());
if (null != $activeElement) {
    $parentElement = $activeElement->getParentMenuElement();
    if (null == $parentElement) { $parentElement = $activeElement; }
    $elements = $this->layout()->menuElementService->getChildrenElements($parentElement);
}
?>
                <div class="coll">
                    <?php if (null != $activeElement) { ?>
                    <article class="module-a hide-on-mobile">
                        <?php if ($this->layout()->page->getSlug() == 'products') { ?>
                        <h1>Select a category</h1>
                            <?php foreach ($this->layout()->brands as $brand) { ?>
                                <?php if ($brand->getName() == 'AVS' || $brand->getName() == 'LUND') { ?>
                        <ul class="list-links" style="border-top: none;">
                            <li style="border-top: 0;"><a class="boldLink" href="/products/<?php echo urlencode(strtolower($brand->getName())); ?>"><h3<?php echo ($this->layout()->slugtwo == urlencode(strtolower($brand->getName())) ? ' style="color:#cc3333;"' : ''); ?>><?php echo strtoupper($brand->getLabel()); ?></h3></a></li>
                                    <?php 
                                    $productCategories = $this->layout()->brandProductCategory->getActiveBrandProductCategoriesByBrand($brand);
                                    foreach ($productCategories as $category) {
                                    ?>
                                        <?php if ($category->getDeleted() == false && $category->getDisabled() == false) { ?>
                            <li<?php echo (($this->layout()->slugthree == urlencode(strtolower($category->getProductCategory()->getName())) && $this->layout()->slugtwo == urlencode(strtolower($brand->getName()))) ? ' class="active"' : ''); ?>><a href="/products/<?php echo urlencode(strtolower($brand->getName())); ?>/<?php echo urlencode(strtolower($category->getProductCategory()->getName())); ?>"><?php echo ucwords(strtolower($category->getProductCategory()->getDisplayName())); ?></a></li>
                                        <?php } ?>
                                    <?php } ?>
                        </ul>
                                <?php } ?>
                            <?php } ?>
                        <?php } else { ?>
                    <h1><?php echo (null != $parentElement ? $parentElement->getTitle() : $activeElement->getTitle()); ?></h1>
                        <ul class="list-links">
                            <?php foreach ($elements as $element) { ?>
                                <?php if ($element->getParentMenuElement()->getMenuElementId() == $parentElement->getMenuElementId()) { ?>
                                <li<?php echo ($activeElement->getMenuElementId() == $element->getMenuElementId() ? ' class="active"' : ''); ?>><a href="<?php echo $element->getUrl(); ?>"><?php echo $element->getTitle(); ?></a></li>
                                <?php } ?>
                            <?php } ?>
                        </ul>
                        <?php } ?>
                    </article>
                    <?php } ?>
                    <?php if ($this->layout()->retailerSearch) { ?>
                    <article class="module-d">
                        <h1>Find a Retailer</h1>
                        <p>To find the closest AVS and LUND retailer, simply enter your zip code and desired distance in the form in the upper left corner. With thousands of local, regional and national retailers carrying our product - there's probably one very close to you.</p>
                        <form name="retailer-search" method="POST" action="/where-to-buy/retailers">
                        <label>Your zip or postal code:</label>
                        <input type="text" name="postCode" id="postCode" value="<?php echo ($this->layout()->rsPostCode ? $this->layout()->rsPostCode : ''); ?>" />
                        <select name="radius" id="radius">
                            <option value="5"<?php echo ($this->layout()->rsRadius == '5' ? ' selected="selected"' : ''); ?>>Within 5 miles</option>
                            <option value="10"<?php echo ($this->layout()->rsRadius == '10' ? ' selected="selected"' : ''); ?>>Within 10 miles</option>
                            <option value="20"<?php echo ($this->layout()->rsRadius == '20' ? ' selected="selected"' : ''); ?>>Within 20 miles</option>
                        </select>
                        <input type="submit" value="Search" name="submit" class="btn btn-search-lg"> 
                        </form>
                    <?php if ($this->layout()->retailers) { ?>
                        <h2 style="margin-top:25px;">Retailers:</h2>
                        <div id="retailers">
                            <?php foreach ($this->layout()->retailers as $retailer) { ?>
                            <div class="retailer">
                                <p class="name"><a href="#" id="map<?php echo $retailer->getRetailerId(); ?>"><?php echo $retailer->getCompanyName(); ?></a></p>
                                <p class="phone">Call <?php echo $retailer->getPhoneNumber(); ?></p>
                                <p class="address"><?php echo $retailer->getStreetAddress(); ?><p>
                                <?php if ($retailer->getExtStreetAddress()) { ?>
                                <p class="address"><?php echo $retailer->getExtStreetAddress(); ?>
                                <?php } ?>
                                <p class="address"><?php echo $retailer->getLocality(); ?>, <?php echo $retailer->getRegion()->getSubdivisionName(); ?> <?php echo $retailer->getPostCode(); ?></p>
                                <p class="directions"><a href="http://maps.google.com/maps?f=d&source=s_d&saddr=&daddr=<?php echo $retailer->getStreetAddress(); ?>,+<?php echo $retailer->getLocality(); ?>,+<?php echo $retailer->getRegion()->getSubdivisionName(); ?>+<?php echo $retailer->getPostCode(); ?>" taret="_blank">Get Directions</a></p>
                        </div>
                            <?php } ?>
                    </article>
                    <?php } ?>
                    <?php } ?>
                    <?php if ($this->layout()->page->getSlug() == 'products' || $this->layout()->page->getSlug() == 'where-to-buy/retailers' || $this->layout()->page->getSlug() == 'where-to-buy/online-retailers') { ?> 
                    <a href="/customer-care/installation">
                        <div class="module-c">
                            <div class="module-icon" style="background-image:url(/assets/application/lundinternational/images/icon_videoBLUEscreen.png);">
                                <h4>Installation<br>Made Easy</h4>
                                <p>See our videos...</p>
                            </div>
                        </div>
                    </a>
                    <a href="/customer-care/product-registration">
                        <div class="module-c">
                            <div class="module-icon" style="background-image:url(/assets/application/lundinternational/images/icon-warrantyBLUEscreen.png);">
                                <h4>Lifetime Warranty<br>Register Your<br>Product Now!</h4>
                            </div>
                        </div>
                    </a>
                    <a href="/about-us/drivers-council">
                        <div class="module-c">
                            <div class="module-icon" style="background-image:url(/assets/application/lundinternational/images/icon-bluecouncil.png);">
                                <h4>Join Our<br>Drivers Council</h4>
                                <p>Share your thoughts.</p>
                            </div>
                        </div>
                    </a>
                    <a href="/about-us/dealers-edge">
                        <div class="module-c">
                            <div class="module-icon" style="background-image:url(/assets/application/lundinternational/images/dealer_starBLUEscreen.png);">
                                <h4>Become a Dealer<br>and Dealers Edge<br>Member Today</h4>
                            </div>
                        </div>
                    </a>
                    <?php } ?>
                    <script type="text/javascript">
                    $(function() {
                        $(".twitter").tweet({
                            join_text: "auto",
                            username: ["lundinter"],
                            avatar_size: 0,
                            count: 2,
                            loading_text: "loading tweets..."
                        });     
                    });
                    </script>
                    <article class="module-a twitter">
                        <h2>Connect with AVS and LUND</h2>
                        <ul class="social">
                            <li><a class="fb" href="http://www.facebook.com/LundInternational" onclick="_gaq.push(['_trackEvent','Facebook','Click on Facebook','Facebook'])" target="_blank" title="Like us on Facebook">Facebook</a></li>
                            <li><a class="tw" href="http://www.twitter.com/LundInter" onclick="_gaq.push(['_trackEvent','Twitter','Click on Twitter','Twitter'])" target="_blank" title="Follow us on Twitter">Twitter</a></li>
                            <li><a class="yt" href="http://www.youtube.com/user/LundInternational" onclick="_gaq.push(['_trackEvent','Youtube','Click on Youtube','Youtube'])" target="_blank" title="Follow us on YouTube">YouTube</a></li>
                            <li><a class="pi" href="http://pinterest.com/lundinter/" onclick="_gaq.push(['_trackEvent','Pinterest','Click on Pinterest','Pinterest'])" target="_blank" title="Follow us on Pinterest">Pinterest</a></li>
                        </ul>
                        <p><strong>Recent Tweets</strong></p>
                    </article>
                </div>
