        <nav class="topnav">
        <div id="topnav-btn"></div>
            <ul class="sfmenu">
            <?php
                $menu = $this->menuService->getMenuByShortCode($this->site, 'main-menu');
                $elements = $this->menuElementService->getParentElements($menu);
                $activeElement = $this->menuElementService->getMenuElementByUrl($menu, '/' . $this->page->getSlug());

                if (null != $activeElement) {
                    $parentElement = $activeElement->getParentMenuElement();
                    if (null == $parentElement) { $parentElement = $activeElement; }
                }

                foreach ($elements as $element) {
                    $childElements = null;

                    if (null == $element->getParentMenuElement()) {
                        $childElements = $this->menuElementService->getChildrenElements($element);
            ?>
                <li<?php if (null != $activeElement) { echo (($activeElement->getMenuElementId() == $element->getMenuElementId() || $parentElement->getMenuElementId() == $element->getMenuElementId()) ? ' class="active"' : ''); } ?>>
                    <a href="<?php echo $element->getUrl(); ?>" title="<?php echo $element->getTitle(); ?>"><?php echo $element->getTitle(); ?></a>
                        <?php if (null != $childElements) { ?>
                     <div class="topnav-subarrow"></div>
                    <ul>
                            <?php foreach ($childElements as $childElement) { ?>
                        <li<?php if (null != $activeElement) { echo ($activeElement->getMenuElementId() == $childElement->getMenuElementId() ? ' class="active"' : ''); } ?>><a href="<?php echo $childElement->getUrl(); ?>"<?php echo ($childElement->getAction() == 'external' ? ' target="_blank"' : ''); ?> title="<?php echo $childElement->getTitle(); ?>"><?php echo $childElement->getTitle(); ?></a></li>
                            <?php } ?>
                    </ul>
                        <?php } ?>
                        <?php if ($element->getUrl() == '/products') { ?>
                        <div class="topnav-subarrow"></div>
                    <ul class="navcols">
                        <li>
                            <?php foreach($this->brands as $brand) { ?>
                                <?php if (strtolower($brand->getName()) == 'avs' || strtolower($brand->getName()) == 'lund') { ?>
                                <ol>
                                    <li><h2><a href="/products/<?php echo strtolower($brand->getName()); ?>"><?php echo strtoupper($brand->getLabel()); ?></a></h2></li>
                                    <?php
                                    $productCategories = $this->brandProductCategory->getActiveBrandProductCategoriesByBrand($brand);
                                    foreach ($productCategories as $category) {
                                    ?>
                                        <?php if ($category->getDisabled() == false && $category->getDeleted() == false) { ?>
                                    <li<?php echo (($this->slugthree == urlencode(strtolower($category->getProductCategory()->getName())) && $this->slugtwo == urlencode(strtolower($brand->getName()))) ? ' class="active"' : ''); ?>><a href="/products/<?php echo urlencode(strtolower($brand->getName())); ?>/<?php echo urlencode(strtolower($category->getProductCategory()->getName())); ?>"><?php echo ucwords(strtolower($category->getProductCategory()->getDisplayName())); ?></a></li>
                                        <?php } ?>
                                    <?php } ?>
                                </ol>
                                <?php } ?>
                            <?php } ?>
                        </li>
                    </ul>
                        <?php } ?>
                </li>
                <?php } ?>
            <?php } ?>
            </ul>
        </nav>
