<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'smart-questions/grades/create'    => __DIR__ . '/view/smart-questions/grades/create.phtml',
    'smart-questions/grades/edit'      => __DIR__ . '/view/smart-questions/grades/edit.phtml',
    'smart-questions/grades/index'     => __DIR__ . '/view/smart-questions/grades/index.phtml',
    'smart-questions/grades/view'      => __DIR__ . '/view/smart-questions/grades/view.phtml',
    'smart-questions/questions/create' => __DIR__ . '/view/smart-questions/questions/create.phtml',
    'smart-questions/questions/edit'   => __DIR__ . '/view/smart-questions/questions/edit.phtml',
    'smart-questions/questions/index'  => __DIR__ . '/view/smart-questions/questions/index.phtml',
    'smart-questions/questions/view'   => __DIR__ . '/view/smart-questions/questions/view.phtml',
    'smart-questions/subjects/create'  => __DIR__ . '/view/smart-questions/subjects/create.phtml',
    'smart-questions/subjects/edit'    => __DIR__ . '/view/smart-questions/subjects/edit.phtml',
    'smart-questions/subjects/index'   => __DIR__ . '/view/smart-questions/subjects/index.phtml',
    'smart-questions/subjects/view'    => __DIR__ . '/view/smart-questions/subjects/view.phtml',
);
